### ISSUE TITLE
[jackett] Cache tracker errors

### ISSUE THREAD

**Issue by mouzzampk2014-zz** [cross-seed/cross-seed#103]
Hi, 

Copied from `jackett` github and some discussion can be found in `cross-seed` Discussions

The goal is to speed up searches. When some indexer is down due to network issues or heavy load it can delay requests for other indexers too. For example, in manual search in Jackett if you select several indexers or multiple trackers or all in `cross-seed`.

This functionality complements the cache.

Thank you

**Comment by mmgoodnow** [comment]
some thoughts: 

this would be convenient to do alongside the torznab migration, we'll want to start `Promise.all()`- ing each tracker's search together, with a timeout that isn't 90 seconds long of course. Maybe 15 sec

**Comment by mouzzampk2014** [comment]
Yup that would be great or cross-seed ignore the tracker until next run that means if cross-seed received one timeout error then leave it until next run. 

I am not sure how `daemon` will work in this case.

**Comment by mmgoodnow** [comment]
looks like I forgot to close this. We did this in February or so
