### ISSUE TITLE
Transmission

### ISSUE THREAD

**Issue by hawkinspaul** [cross-seed/cross-seed#105]

**Comment by mmgoodnow** [comment]
To get this implemented, please provide documentation for Transmission's API.

**Comment by arbitrarypunter** [comment]
Transmission API docs are available here: https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt

In case it helps anyone using transmission with cross seed in the meantime. I run this script every 4 hours out of cron to search for cross seeds: https://pastebin.com/UrPSCF84
The torrentsDir value in the script should match whatever you have set for outputDir in your cross-seed config file.

**Comment by scatking** [comment]
It would be great if transmission can be supported :)

**Comment by techguruz** [comment]
ok well plus one on this then lol

**Comment by mmgoodnow** [comment]
Transmission support is in the top 3 feature priorities for me right now, but bugs and docs take precedence over features as well and I'm running on very limited time these last few months. Please hang tight!

**Comment by mmgoodnow** [comment]
I keep the [roadmap](https://github.com/orgs/cross-seed/projects/1/views/1) relatively up to date, btw, so you can keep tabs

**Comment by mmgoodnow** [comment]
Transmission support has been added in the `next` branch! Use `-A inject --transmission-rpc-url http://user:pass@host:port/transmission/rpc` on the command line, or you can use `action: "inject", transmissionRpcUrl: "http://user:pass@host:port/transmission/rpc"` in the config file. 


Please test out the branch if you can. On Docker, you can pull the `next` tag. Without docker, you can clone the repo and run it locally.

**Comment by elboletaire** [comment]
I tried with a fresh install of cross-seed using the `next` branch, and everything I get are migration errors:

~~~
migration file "02-timestamps" failed
migration failed with error: select `id` as `id`, `url` as `url`, `apikey` as `apikey`, `active` as `active`, `status` as `status`, `status_updated_at` as `statusUpdatedAt`, `search_cap` as `searchCap`, `tv_search_cap` as `tvSearchCap`, `movie_search_cap` as `movieSearchCap` from `indexer` where `active` = true - no such column: apikey

/home/elboletaire/docker/cross-seed/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                           ^
SqliteError: select `id` as `id`, `url` as `url`, `apikey` as `apikey`, `active` as `active`, `status` as `status`, `status_updated_at` as `statusUpdatedAt`, `search_cap` as `searchCap`, `tv_search_cap` as `tvSearchCap`, `movie_search_cap` as `movieSearchCap` from `indexer` where `active` = true - no such column: apikey
    at Database.prepare (/home/elboletaire/docker/cross-seed/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
    at executeQuery (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/execution/runner.js:300:20)
    at async Runner.run (/home/elboletaire/docker/cross-seed/node_modules/knex/lib/execution/runner.js:30:19)
    at async syncWithDb (file:///home/elboletaire/docker/cross-seed/dist/torznab.js:140:24)
    at async Object.up (file:///home/elboletaire/docker/cross-seed/dist/migrations/02-timestamps.js:15:5) {
  code: 'SQLITE_ERROR'
}

Node.js v18.13.0
~~~

Also tried executing it after having the database created with version 4.3.8, and the error is the same.

**Comment by mediadev123** [comment]
> I tried with a fresh install of cross-seed using the `next` branch, and everything I get are migration errors:

Has anyone found a solution to fix this yet? Can I just create this column in sqlite manually?

**Comment by mmgoodnow** [comment]
The `next` branch is ready for fresh installs. Please try it out!

**Comment by Ghostwritertje** [comment]
It seemed to be working a few days ago, but now I'm getting an error after pulling the new image:

`error: Failed to reach Transmission at http://[REDACTED]:[REDACTED]@transmission:9091/transmission/rpc`

**Comment by deskmonster** [comment]
Same here
Configuration file already exists.
info: Validating your configuration...
error: Failed to reach Transmission at http://username:[REDACTED]@127.0.0.1:9091/transmission/rpc/

Tried both with and without reverse proxy

**Comment by mmgoodnow** [comment]
Thanks for testing folks! Transmission connections should be working again

**Comment by deskmonster** [comment]
When I use deamon mode with rss
```
info: Validating your configuration...
info: Your configuration is valid!
info: [server] Server is running on port 2468, ^C to stop.
info: [scheduler] rss: last run never, next run in 0ms
info: [scheduler] starting job: rss
error: Cannot read properties of undefined (reading 'signal')
```
I disable rss and test with api,but nothing reply to me from docker logs 
```
curl -s -X POST http://127.0.0.1:2468/api/webhook \
  -H 'Content-Type: application/json' \
  -d infoHash="${TR_TORRENT_HASH}"
```
So I decide to test search mode
```
Configuration file already exists.
info: Validating your configuration...
info: Your configuration is valid!
info: [search] Found 420 torrents, 82 suitable to search for matches
info: [1/82] Searching for Amovie-group
info: [torznab] Searching 23 indexers for Amovie-group.mkv
error: error searching for Amovie-group.mkv
info: [2/82] Searching for another.movie-group.mkv
info: [torznab] Searching 23 indexers for another.movie-group.mkv
error: error searching for another.movie-group.mkv
file:///usr/src/cross-seed/node_modules/node-fetch/src/index.js:70
                        const error = new AbortError('The operation was aborted.');
                                      ^

AbortError: The operation was aborted.
    at abort (file:///usr/src/cross-seed/node_modules/node-fetch/src/index.js:70:18)
    at AbortSignal.abortAndFinalize (file:///usr/src/cross-seed/node_modules/node-fetch/src/index.js:89:4)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
    at abortSignal (node:internal/abort_controller:292:10)
    at AbortController.abort (node:internal/abort_controller:323:5)
    at Timeout._onTimeout (file:///usr/src/cross-seed/dist/torznab.js:246:29)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  type: 'aborted'
}
```

That's what I get for all

**Comment by Ghostwritertje** [comment]
I can search just fine right now. Snatching of the torrent files fails however:
>2023-02-08 09:46:39 [36mverbose [39m: [decide] [REDACTED_BY_ME] - it has a different file tree
>2023-02-08 09:46:41 [31merror [39m: snatching http://prowlarr:9696/1/download?apikey=[REDACTED]&link=[REDACTED_BY_ME]&file=[REDACTED_BY_ME] timed out

I suspect an unexpected result of the filtering of the inactive indexers.

**Comment by mmgoodnow** [comment]
@deskmonster what's your node version?

**Comment by deskmonster** [comment]
> @deskmonster what's your node version?

I'm using docker for testing. So the node version should be just as the image cross-seed:next

**Comment by Ghostwritertje** [comment]
Could I request that torrents in transmission are no longer added in a `paused` state? If Cross-seed is supposed to be fully automatic, it doesn't seem to make a whole lot of sense that they have to be manually started.

**Comment by elboletaire** [comment]
Well I decided to try again with the latest version in next branch, and this is what happened after trying to use it (from a working 4.3.8 version to migrate from, tried with node 16 and node 18):

~~~
migration file "02-timestamps" failed
migration failed with error: create table `indexer` (`id` integer not null primary key autoincrement, `url` varchar(255), `apikey` varchar(255), `active` boolean) - table `indexer` already exists

~/cross-seed/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                           ^
SqliteError: create table `indexer` (`id` integer not null primary key autoincrement, `url` varchar(255), `apikey` varchar(255), `active` boolean) - table `indexer` already exists
    at Database.prepare (~/cross-seed/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (~/cross-seed/node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
    at executeQuery (~/cross-seed/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (~/cross-seed/node_modules/knex/lib/client.js:146:12)
    at ~/cross-seed/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at trxClient.query (~/cross-seed/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (~/cross-seed/node_modules/knex/lib/execution/runner.js:123:36)
    at Runner.queryArray (~/cross-seed/node_modules/knex/lib/execution/runner.js:217:21)
    at Runner.queryArray (~/cross-seed/node_modules/knex/lib/execution/runner.js:269:31) {
  code: 'SQLITE_ERROR'
}
~~~

Using a fresh install (removing db) worked tho! It properly injects torrent files to transmission but, as Ghostwritertje noted in the previous message, they're added paused.

**Comment by mmgoodnow** [comment]
we fixed the adding them paused thing (i had just accidentally left it in during my testing). they're still not starting?

**Comment by mmgoodnow** [comment]
your migration bug was expected - i reordered some of the migrations in the branch so a database that had been created from a previous version of the branch is a no-go. Deleting that database was the right thing to do!

**Comment by elboletaire** [comment]
I'm just giving it a second try, after the first one gone right, and now every torrent it finds is trying to inject them again and fails with an error from transmission
![imatge](https://user-images.githubusercontent.com/153305/219820568-d8faebaf-c7aa-4909-b95b-f565938e8526.png)
![imatge](https://user-images.githubusercontent.com/153305/219820545-83a42e71-3fa9-4816-9a99-02faf9f8a2d2.png)

Note these were properly injected in the previous run.

**Comment by mmgoodnow** [comment]
can you find those errors in `logs/verbose.current.log` and see what the errors are that got logged below them?

**Comment by elboletaire** [comment]
The error just says "duplicate torrent", because as said, the torrents were properly injected in the previous run. Is like cross-seed is not properly detecting them as duplicated.

Here's the exact output from the log file, just in case:

~~~
2023-02-18 01:22:22 verbose: [decide] Future-High_Off_Life-CD-FLAC-2020-CALiFLAC - no match for IPTorrents torrent Future-High Off Life-CD-FLAC-2020-CALiFLAC - the info hash matches a torrent you already have (cached)
8595   │ 2023-02-18 01:22:22 error: [transmission] Transmission responded with an error
8596   │ 2023-02-18 01:22:22 debug: Transmission responded with error: "duplicate torrent"
8597   │ 2023-02-18 01:22:22 error: Found Future-High_Off_Life-CD-FLAC-2020-CALiFLAC on AlphaRatio - failed to inject, saving instead

 2023-02-18 01:23:15 verbose: [decide] Gang_Starr-Step_In_The_Arena-CD-FLAC-1990-THEVOiD_INT - no match for IPTorrents torrent Gang Starr-Step In The Arena-CD-FLAC-1990-THEVOiD INT - the info hash matches a torrent you already have (cached)
8866   │ 2023-02-18 01:23:15 error: [transmission] Transmission responded with an error
8867   │ 2023-02-18 01:23:15 debug: Transmission responded with error: "duplicate torrent"
8868   │ 2023-02-18 01:23:15 error: Found Gang_Starr-Step_In_The_Arena-CD-FLAC-1990-THEVOiD_INT on AlphaRatio - failed to inject, saving instead
~~~

**Comment by mmgoodnow** [comment]
@elboletaire this bug with duplicate torrents should be fixed as of the currently-building build!

**Comment by elboletaire** [comment]
> @elboletaire this bug with duplicate torrents should be fixed as of the currently-building build!

Indeed the "slight hack" worked 😉

**Comment by elboletaire** [comment]
I've just removed some cross-seed torrents to check the "adding them as paused thing" and it still adds them paused... I've checked the code (up to date as you know), and I see [you're properly setting them as `paused: false`](https://github.com/cross-seed/cross-seed/blob/next/src/clients/Transmission.ts#L156), so there's probably an upstream issue.

**Comment by mmgoodnow** [comment]
There must be some other undocumented thing I have to do…

**Comment by arbitrarypunter** [comment]
If you are on Transmission 4, there's an outstanding bug which is causing torrents to be paused on add: https://github.com/transmission/transmission/issues/4740

**Comment by elboletaire** [comment]
> If you are on Transmission 4, there's an outstanding bug which is causing torrents to be paused on add: [transmission/transmission#4740](https://github.com/transmission/transmission/issues/4740)

I actually thought I linked to that in a previous comment but seems like I forgot clicking on "comment" 😂
