### ISSUE TITLE
After the latest update cross-seed isn't honoring the original paths !!!

### ISSUE THREAD

**Issue by TRaSH-** [cross-seed/cross-seed#200]
After the latest update i noticed that cross-seed torrents doesn't honor the paths from the existing torrents.

I've in the the default save path `/data/torrents/tv` and in that folder i've subfolders `hd` and `uhd` 

cross seed should honor the original path like it used to !

Example: using the latest release.

![image](https://user-images.githubusercontent.com/6155095/155838353-239aab3e-5afc-412f-a3dd-c268727653f0.png)

as you can see the original is using `/data/torrents/tv-hd/`
and the cross seed is using the `/data/torrents/tv/` 

switched back to  `mmgoodnow/cross-seed:version-3.3.0`
and it works like it should.

![image](https://user-images.githubusercontent.com/6155095/155838893-61380611-9d2d-4b41-baeb-3b74a6856c78.png)

Hope this can be fixed in the next update.

**Comment by mmgoodnow** [comment]
Please comment on #74 with your findings
