### ISSUE TITLE
Arm support for docker

### ISSUE THREAD

**Issue by 2fst4u** [cross-seed/cross-seed#297]
Request support for arm architecture in the docker image.

**Comment by mmgoodnow** [comment]
Not familiar with docker for arm, do you know what the differences are? Is it just changing the base image?

**Comment by 2fst4u** [comment]
I wouldn't dare to speculate because I'm not a software guy but I just know the image needs to be built for the architectures separately.

On dockerhub in the tags section you can see which architecture is supported and if arm isn't supported then it won't run on arm at all unfortunately.

**Comment by mdwkelly** [comment]
interested in this as well as just moved over to using a pi4 for my own seedbox.

Thanks

**Comment by mmgoodnow** [comment]
For now I recommend building manually from the dockerfile.

**Comment by mdwkelly** [comment]
Thanks.

A bit above my pay grade but always up for learning something new.

Cheers

**Comment by mmgoodnow** [comment]
done.

**Comment by mdwkelly** [comment]
Thank you, appreciated.

Will give it a go shortly
Cheers

**Comment by 2fst4u** [comment]
What tag is it under @mmgoodnow ? I can't see it on dockerhub.

**Comment by mmgoodnow** [comment]
mmgoodnow/cross-seed is no longer being pushed

**Comment by 2fst4u** [comment]
With the correct image I'm getting the following error:

`Error: failed to create containerd task: failed to create shim task: OCI  runtime create failed: runc create failed: unable to start container process: exec:  "daemon": executable file not found in $PATH: unknown'`

I've tried passing the daemon command and omitting the command and it gives an error either way.

**Comment by 2fst4u** [comment]
I hate when this happens but I may have spoken too soon. It might be because I previously pulled the old wrong image (I'm on kubernetes) and it might have been caching it. The pod keeps restarting but I imagine it's probably because I don't have the daemon running yet and it's just exiting.

It generated a config with gen-config so it must be doing something.

**Comment by jaum20** [comment]
> crossseed/cross-seed

Why am I getting this error:

```
Unable to find image 'crossseed/cross-seed:latest' locally
latest: Pulling from crossseed/cross-seed
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
```
