### ISSUE TITLE
Support for armv7 (Rpi4b 32bits)

### ISSUE THREAD

**Issue by nikogaug** [cross-seed/cross-seed#301]
Hello,
I tried several times to recreate a container from Dockerfile, but I couldn't.
Do you think it is possible to make an image available that is compatible with Rpi4b, Raspberry Pi OS 32bits in armv7?
Thanks for everything ! \o/
Nikogaug.

**Comment by bakerboy448** [comment]
32bit systems and support is generally being depreciated these days.

there's absolutely no reason at all to be running a 32bit OS especially on x64 hardware

reinstall with an OS that doesn't artificially limit your hardware and reduce compatibility with most things / that will only increasingly cause headaches

**Comment by nikogaug** [comment]
Yes you're right. I have to change my OS. Thanks again.
