### ISSUE TITLE
Feature request: Add option to retry configuration validation after set time

### ISSUE THREAD

**Issue by say-no-to-deer-pressure** [cross-seed/cross-seed#303]
I am running cross-seed in a docker on Unraid with prowlarr.
When all of my dockers are stopped and then started again, cross-seed is able to start before prowlarr can, so the configuration validation fails with the following errors, and cross-seed doesn't start.

```
info: Validating your configuration...
warn: Failed to reach http://192.168.1.171:9696/5/api?apikey=[REDACTED]
warn: Failed to reach http://192.168.1.171:9696/7/api?apikey=[REDACTED]
warn: Failed to reach http://192.168.1.171:9696/3/api?apikey=[REDACTED]
warn: Failed to reach http://192.168.1.171:9696/8/api?apikey=[REDACTED]
warn: Failed to reach http://192.168.1.171:9696/9/api?apikey=[REDACTED]
warn: Failed to reach http://192.168.1.171:9696/11/api?apikey=[REDACTED]
warn: Failed to reach http://192.168.1.171:9696/13/api?apikey=[REDACTED]
error: no working indexers available
```

Would it be possible to add an option to allow cross-seed to retry its validation after a few seconds if it fails initially?
Or if you see any other potential work-around to avoid this,  I would appreciate the advice.

Thanks.

**Comment by mouzzampk2014** [comment]
Yes that would be nice 👌 but in meantime you can use depends on option to start the cross seed once prowlarr is up and running. 

I hope that help for time being.

**Comment by say-no-to-deer-pressure** [comment]
> Yes that would be nice 👌 but in meantime you can use depends on option to start the cross seed once prowlarr is up and running.
> 
> I hope that help for time being.

Unfortunately Unraid doesn't have startup dependency support as far as I can tell, but I did just learn that you can alter the order the containers start up in simply by dragging them around in the Docker page. Up until new I had them in alphabetical order because I didn't know the order they were listed had any bearing on functionality. I'll try dragging cross-seed to the very bottom and see if that fixes it. You can also set a wait time for the container to start.

I think with these two options this should fix my issue.
