### ISSUE TITLE
Docker environment doesn't automatically create the config file on the first run like it claims

### ISSUE THREAD

**Issue by daemonofchaos** [cross-seed/cross-seed#305]
When attempting to start a new cross-seed container on Unraid, it fails and the logs report:

`error: required option '-i, --torrent-dir <dir>' not specified`

**Comment by mmgoodnow** [comment]
you need to specify the option. Usually, this option gets specified by an automatically-created config file the first time you run the Docker container - make sure that cross-seed's config directory isn't owned by root with `sudo chown -R 1000:1000 /path/to/config/dir` - or use a different uid/gid if you're running cross-seed as a different uid/gid

**Comment by mmgoodnow** [comment]
actually, I looked into this some more and it's a bug. Fix coming soon!

**Comment by mmgoodnow** [comment]
v4.3.4 has this fix, and it should be published to Docker within the next 15 minutes.
