### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by mmgoodnow** [cross-seed/cross-seed#312]
first reported by @KyleSanderson

**Comment by mmgoodnow** [comment]
did a little bit of profiling and it looks like XML parsing might be a significant cost

**Comment by mmgoodnow** [comment]
was able to repro this behavior. It looks like cross-seed's CPU spikes during RSS scans. I can't fully tell what's causing the problem but it might be related to the fuzzy search. One symptom is that the event loop gets so backed up that the logger isn't able to actually flush its logging queue until the spiking is over

**Comment by mmgoodnow** [comment]
OK yeah. I got a profiling log from my prod instance and it's a pretty clear smoking gun: 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/9119498/210156531-9c915994-7b42-4f79-815b-b77270244ad8.png">

I'm not really sure there's any way to make the fuzzy searching less expensive, but we can definitely do _wayyy_ less of it which should probably be enough.

**Comment by mmgoodnow** [comment]
fixed in #341

**Comment by KyleSanderson** [comment]
thanks man, I'm still relying on cross-seed for 17.68% of my crosses. Can you please pin a new release when you have a moment.
