### ISSUE TITLE
qBittorrent 403 on login

### ISSUE THREAD

**Issue by mmgoodnow** [cross-seed/cross-seed#313]
might be related to special chars in pw?

**Comment by sjtuross** [comment]
Got login failed since 4.3.5. 4.3.4 works.

**Comment by mmgoodnow** [comment]
@sjtuross did you also upgrade qBittorrent at the same time?

**Comment by sjtuross** [comment]
Not yet as I use linuxserver/qbittorrent image which hasn't upgraded to 4.4.4.

**Comment by mmgoodnow** [comment]
fixed in v4.3.6
