### ISSUE TITLE
Failed to reach prowlarr api

### ISSUE THREAD

**Issue by Cealor** [cross-seed/cross-seed#317]
When starting cross-seed (as daemon) in docker it exits after a some seconds with this error:
```
Configuration file already exists.
info: Validating your configuration...
warn: Failed to reach http://192.168.1.3:9696/3/api?apikey=[REDACTED]
error: no working indexers available
```
When trying with `localhost` or `127.0.0.1` it fails immediately. It also fails with other indexers.
The api key is correct, as is the indexer config in prowlarr.

**Comment by bakerboy448** [comment]
- Local host will never work in docker as it's the container itself 
- The server IP only works if everything is in host as far as I understand it
- Everything should be in the same docker compose and thus on the same little internal docker network and then you can and should just use the container name

**Comment by mmgoodnow** [comment]
is your Prowler instance running in Docker also?

**Comment by mmgoodnow** [comment]
if they're both in docker and on the same docker-compose, then you should use `http://prowlarr:9696/3/api?apikey=[REDACTED]`

if only cross-seed is in docker, then you should use `http://172.17.0.1:9696/3/api?apikey=[REDACTED]`

if they're in separate docker-composes, then put them into the same docker-compose.
