### ISSUE TITLE
Was the '--search-all' option deprecated?

### ISSUE THREAD

**Issue by 07416** [cross-seed/cross-seed#319]
[the original pull request from 2020](https://github.com/cross-seed/cross-seed/commit/6d702d15835028a6134b4b9f94e5a6278014d3fc)

    cross-seed --version : 

     4.3.8

both the flag and its alias are reported as unknown options by the program:

    error: unknown option '--search-all'  
    error: unknown option '-a'

To clarify, the setting searches for all files instead of video-only torrent data. For instance, I've cross-seed between two music trackers.

**Comment by bakerboy448** [comment]
Yes.

https://www.cross-seed.org/docs/tutorials/v4-migration-guide

**Comment by 07416** [comment]
[sorry, I accidentally submitted to issues instead of [discussions](https://github.com/cross-seed/cross-seed/discussions/)]

**Comment by 07416** [comment]
> https://www.cross-seed.org/docs/tutorials/v4-migration-guide

Great, I clearly didn't crawl through the entire website.

```
--include-non-videos  
--include-episodes
```
