### ISSUE TITLE
cross-seeded directory structure includes top-level directory named "_"

### ISSUE THREAD

**Issue by TheReclusiveFox** [cross-seed/cross-seed#320]
As per discord discussion https://discord.com/channels/880949701845872672/880949702349164556/1017187328734789692, cross-seed injected a torrent but included a top level folder, "_", containing the files causing the client to indicate missing files

```
root@foxden:~# docker exec -it cross-seed cross-seed --version
Configuration file already exists.
4.3.8
```

**Comment by mmgoodnow** [comment]
fixed in the v5 development branch `next`
