### ISSUE TITLE
can no longer login to qbit getting a 405

### ISSUE THREAD

**Issue by DuzAwe** [cross-seed/cross-seed#325]
All API methods only allows GET or POST methods. Use POST when you are mutating some state (or when your request is too big to fit into GET) and use GET otherwise. Starting with qBittorrent v4.4.4, server will return 405 Method Not Allowed when you used the wrong request method. - https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)

Looks like they have changed how auth works. Current config set up fails.

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/cross-seed/cross-seed/issues/310

This was already fixed

**Comment by DuzAwe** [comment]
Didn't see that docker is now crossseed/cross-seed. Closing
