### ISSUE TITLE
handle torznab limits - query and grab

### ISSUE THREAD

**Issue by bakerboy448** [cross-seed/cross-seed#327]
handle torznab grab and api limits and back off rather than continuing to hammer

prowlarr

```
2022-10-23 14:42:53.1|Warn|ProwlarrErrorPipeline|API Error:
BadRequest: Grab limit reached
```

cross seed error
```
2022-10-23 16:42:59 [31merror[39m: error downloading torrent at http://localhost:9696/prowlarr/44/download?apikey=[REDACTED]&link=YnR4eWJMYW9iN2NXREJ1Q3dqL3k0YUErenhRQ3V2OVlrK2VwdUhqeTNzMzdVbld1YlBScXZmam14V0ZWRTAzNWdSaTlrczhJTHVlS283QitXdVRJaW8xUENtVml6NXBxY0JRZDNrRmJUTzdwVFdOSUdZR2g5ckVyZWlNSitCMmpTOWVKTXNqYXJzMktyYTJUMUZMdERBNDY0QUl5Qnc4Vy9VYlpUQy9takVhTDU4a3FsQ3hwUVZzdkpQV0lnQXR4&file=Blue+Bloods+S13E03+720p+AMZN+WEB-DL+DD%2B+5.1+H.264-NTb: 400 Bad Request
2022-10-23 16:42:59 [34mdebug[39m: response: {
  "message": "BadRequest: Grab limit reached",
  "content": "Grab limit reached"
}
2022-10-23 16:42:59 [34mdebug[39m: headers: {
  connection: 'close',
  'content-type': 'application/json',
  date: 'Sun, 23 Oct 2022 21:42:59 GMT',
  server: 'Kestrel',
  'cache-control': 'no-cache,no-store',
  expires: '-1',
  pragma: 'no-cache',
  'transfer-encoding': 'chunked'
}

```

**Comment by mmgoodnow** [comment]
Is this a prowlarr-specific api response?

Any way it could return 429?

**Comment by mmgoodnow** [comment]
Definitely agree that this is important work tho

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/pull/1168

**Comment by KyleSanderson** [comment]
Jackett has a cache, Prowlarr refuses to implement it for one reason or another... this is a Prowlarr issue.

**Comment by bakerboy448** [comment]
prowlarr not having a cache has nothing to do with hitting per indexer query/grab limits?

**Comment by mmgoodnow** [comment]
I agree. Caching != respecting rate limits

Regardless, it's been implemented.

**Comment by KyleSanderson** [comment]
> prowlarr not having a cache has nothing to do with hitting per indexer query/grab limits?

Of course it does, if you have 4 clients hitting the RSS feed you've increased the amplification factor by 4x. If you use Jackett, it's still 1x. Prowlarr is still not a good citizen in this regard.

**Comment by bakerboy448** [comment]
> 4 clients hitting the RSS feed you've increased the amplification factor by 4x.

you have 4 clients making the exact same query to the exact same sites within X minutes of each other?  Seems extremely unlikely and that is the only scenario where a cache would make any sense.

Regardless has no relevance to this GHI at all and only serves to add spam.

**Comment by bakerboy448** [comment]
Relevant GHI for Prowlarr HTTP 200 => HTTP 429 
https://github.com/Prowlarr/Prowlarr/issues/1416

**Comment by KyleSanderson** [comment]
> > 4 clients hitting the RSS feed you've increased the amplification factor by 4x.
> 
> you have 4 clients making the exact same query to the exact same sites within X minutes of each other? Seems extremely unlikely and that is the only scenario where a cache would make any sense.
> 
> Regardless has no relevance to this GHI at all and only serves to add spam.

Cross-Seed runs a RSS search every (min) 10 minutes. This, per indexer, runs 144 times per day. If you run 4 clients, you're now hitting that same indexer 576 times per day. More for more consumers, less for less. There's a lot of arrogance here for a well defined (and solvable) problem, and slamming trackers, adding backoffs in other products because of it doesn't further the cause. I am very surprised Prowlarr isn't banned on every tracker because of it.

I've seen a couple edits, and it looks like you're still missing the plot. I've brought it up a number of times with you guys, and have gotten similar responses. This is absolutely related not only to this issue, but every issue where Prowlarr continues to operate in bad faith.

**Comment by bakerboy448** [comment]
@KyleSanderson  Please quit violating GitHub Community Guidelines and spamming this GHI with a completely unrelated topic.

If you wish Prowlarr to add a cache, then open a feature request for Prowlarr.

Again, Prowlarr caching has nothing to do with Cross Seed handling rate limits for torznab and has nothing to do with cross-seed.

**Comment by bakerboy448** [comment]
Prowlarr pending PR to make the response a HTTP 429 (with the existing content)

https://github.com/Prowlarr/Prowlarr/pull/1417

**Comment by bakerboy448** [comment]
Prowlarr master now responds with 429 and  Retry-After in headers
