### ISSUE TITLE
Output update to show how many inject vs pre-existing torrents

### ISSUE THREAD

**Issue by pythonkenyard** [cross-seed/cross-seed#332]
Hopefully simple request.

The output e.g.
Found 71 cross seeds from 47 original torrents

can this be expanded similar to below.
Found 71 cross seeds from 47 original torrents
10 new torrents injected 
61 pre-existing torrents ignored.

Would need to add either 1 or two new counters depending if its injected or existing already.
Easiest would be an injected check, and then the final "pre-existing" value would just be total - injected.

**Comment by mmgoodnow** [comment]
gonna tack this on to #116
