### ISSUE TITLE
Change better-sqlite3 dependency

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [cross-seed/cross-seed#336]
Great project.  Thank you for your work.

cross-seed currently has a dependency on `better-sqlite3` at `"^7.5.0"`.  However version 7 [will not compile against nodejs 19](https://github.com/WiseLibs/better-sqlite3/issues/891).  The fix has necessitated a new major release.

To allow compiling of this project, I believe the dependency needs to allow version 8, either by bumping the `"^7.5.0"` in `package-lock.json`, or changing it to `">7.5.0"` which should allow a major release increase.

**Comment by mmgoodnow** [comment]
fixed in the v5 development branch `next`
