### ISSUE TITLE
[bug] Missing CLI options to disable `includeEpisodes` and `includeNonVideos`

### ISSUE THREAD

**Issue by mynameisbogdan** [cross-seed/cross-seed#337]
Hello,

According to [this](https://www.cross-seed.org/docs/reference/options#includeepisodes) and [also this](https://www.cross-seed.org/docs/reference/options#includenonvideos) there should be the possibility to use `cross-seed search --no-include-episodes` and `cross-seed search --no-include-non-videos` but sadly it seems they're missing and I can't find any way to disable both this options in `search`, but keep them enabled via configuration for `rss`.

```bash
# cross-seed --version
Configuration file already exists.
4.3.8
# cross-seed search --verbose --no-include-episodes
Configuration file already exists.
error: unknown option '--no-include-episodes'
# cross-seed search --verbose --no-include-non-videos
Configuration file already exists.
error: unknown option '--no-include-non-videos'
```

**Comment by mmgoodnow** [comment]
implemented in `next` branch
