### ISSUE TITLE
Trigger a bulk search

### ISSUE THREAD

**Issue by Undrog** [cross-seed/cross-seed#340]
```
usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39
    const response = await statement.run(bindings);
```

While running "cross-seed search" manually, after processing several entries.

I also have my torrent client calling api/webhook upon torrent completion, and autobrr calling api/announce upon announces, my guess is one of these API calls resulted in the database being locked, causing "cross-seed search" to crash.

Of course with an API we can expect requests to come anytime, even if other processes are running. I'm not much of a programmer, but I guess some kind of routine for cross-seed search (or for any operation that requires DB access really) would detect that the database is already locked and wait for the lock to be lifted (maybe with a max timeout to avoid looping indefinitely?)

**Comment by Undrog** [comment]
I guess the actual issue here might be that this causes two instances of cross-seed to be run simultaneously, where as even with the API and daemon mode, there is only one running at a time?

So maybe this is more of a feature request... how can I run a search manually while the daemon is running? I see there is a api/search endpoint mentioned... but this is not documented and I guess this takes a single torrent only, and does not replace the full "cross-seed search" functionality?

It is desirable to trigger a manual search _without_ stopping the daemon in certain cases, like trying to seed a new tracker.

**Comment by mmgoodnow** [comment]
> trying to seed a new tracker

you might be interested in per indexer timestamps (#299). it's not in master yet but it's been merged into my v5 development branch. Still, I do see the value of being able to initiate a bulk search within the already running instance of cross-seed.

**Comment by mmgoodnow** [comment]
oh actually just realized I've already got this listed in the Web UI issue (#307)
