### ISSUE TITLE
Bind Address

### ISSUE THREAD

**Issue by brettpetch** [cross-seed/cross-seed#342]
Currently the application has no way of binding to a specific address to prevent external access.\

The feature that I'd like to propose is a `host` parameter that can be set to a specified ip address in the config file or a localhost switch to the daemon cmd to prevent unauthorized access to the application when it is running. This would be secure enough for a typical server environment and would close a gaping hole, allowing users to implement their own auth at the reverse proxy level if they deem in necessary.

**Comment by mmgoodnow** [comment]
implemented in the v5 development branch `next`
