### ISSUE TITLE
Deluge torrentDir configuration: "announce" api (from autobrr)

### ISSUE THREAD

**Issue by GitHubMilo** [cross-seed/cross-seed#350]
So, I have "torrentDir" defined as the deluge/state directory.
Autobrr is then calling the "announce" endpoint with cross-seed in daemon mode.

Test download:
```
2023-01-04 19:59:16 verbose: [server] Received announce: TVSHOW.S01E05.INTERNAL.1080p.HEVC.x265-MeGusta
2023-01-04 19:59:17 verbose: [rtorrent] Calling method download_list with params []
2023-01-04 19:59:17 verbose: [rtorrent] Calling method system.multicall with params [ [ { methodName: 'd.is_multi_file',
      params: [ 'BA3BEE763FE739ED16A01811A7C6AB7B6F4BFAE2' ] },
    { methodName: 'd.directory',
      params: [ 'BA3BEE763FE739ED16A01811A7C6AB7B6F4BFAE2' ] },
    { methodName: 'd.complete', params: [ 'BA3BEE763FE739ED16A01811A7C6AB7B6F4BFAE2' ] } ] ]
2023-01-04 19:59:17 error: result is not iterable
2023-01-04 19:59:17 debug: Failure caused by server response below:
2023-01-04 19:59:17 debug: [
  { faultCode: -501, faultString: 'Could not find info-hash.' },
  { faultCode: -501, faultString: 'Could not find info-hash.' },
  { faultCode: -501, faultString: 'Could not find info-hash.' }
]
2023-01-04 19:59:17 error: Cannot destructure property 'dataDir' of '(intermediate value)' as it is undefined.
```

**Comment by bakerboy448** [comment]
If you're using deluge, why did you configure it as rtorrent?

deluge is not supported https://github.com/cross-seed/cross-seed#cross-seed-fully-automatic-no-false-positives

**Comment by GitHubMilo** [comment]
Hello.

If Deluge isn't supported, it probably should be removed from the config file:
https://github.com/cross-seed/cross-seed/blob/master/src/config.template.cjs

The reason for running rTorrent as my cross-seed client is simply because some private trackers (won't name them) use the same hash as another (and just change the tracker).
This means it won't load in the first (primary) client.

Deluge seems to be far better tuned on my seedbox (vs. rtorrent) for racing and ratios are great vs. what I get in rTorrent.

**Comment by bakerboy448** [comment]
You've configured cross-seed to lookup torrents from deluge and then add them to rtorrent. That's not supported

**Comment by GitHubMilo** [comment]
OK, fair enough.
