### ISSUE TITLE
Bulk searches don't pick up where they left off

### ISSUE THREAD

**Issue by balpokey** [cross-seed/cross-seed#355]
Hey so currently we can set a schedule with setting the searchCadence in the config file. The cadence seems to be based on the end of the last run. I think it would be good to add a configuration to allow scheduling based off of cron syntax. This way can define when each run starts more explicitly.

Suggestions: 
1. We can set the cron syntax in the searchCadence key
`searchCadence: 0 0 * * 1` for every Monday at midnight
`searchCadence: 0 0 1 * *` first day of every month at midnight
2. We can set cron in a new key
`searchCron: 0 0 * * 1` for every Monday at midnight
`searchCron: 0 0 1 * *` first day of every month at midnight

**Comment by mmgoodnow** [comment]
Why do you think it would be good?

**Comment by balpokey** [comment]
For me it would be really useful because on my system (using Unraid OS) I have it setup to backup all my docker volumes on a weekly basis. Part of the process is to stop all running containers so no reads and writes occur during backup. 

With the current setup of the searchCadence, it is unpredictable when each run will occur. If my cross-seed container stops during a search, the next time the container is started, it doesn't seem to finish out whatever hadn't been searched. So with the cron syntax, it would allow us to explicitly define the start of each search, and better allow us to schedule our searches to coordinate with any other tasks are running our system.

**Comment by mmgoodnow** [comment]
What if cross seed picked up where it left off better?

**Comment by balpokey** [comment]
Yeah, that would also work. Either option would resolve my issue 🙂
