### ISSUE TITLE
Feature request: Ignore .nfo and .srt files

### ISSUE THREAD

**Issue by Fuzzydroid** [cross-seed/cross-seed#357]
As it stands, if a video file folder has any non video file in it, like .nfo or .srt it is excluded from the scan unless `includeNonVideos: true` is set. The problem with this is that setting will also cause all games, books, software, music and so on to also scan.

Is it possible to add a flag for ignoring non video files as long as they are in a folder with a video file?

Many thanks.

**Comment by Fuzzydroid** [comment]
> This has been discussed many times before. Please search the Issues and you'll find the multiple issues discussing this

The dev told me on discord to make a post about it.

**Comment by zakkarry** [comment]
I agree, currently having an issue where single file video torrents are initially grabbed and cross-seed candidates are being excluded based on cross-seed finding a torrent that has a nfo file or .srt file included with the video file, "file tree is different" being the reason. 

This certainly seems avoidable with either a "if file size of different files is < X KB" or "matches .ext" configuration, would benefit this situation greatly.

Look forward to seeing this integrated.

**Comment by zakkarry** [comment]
> Here is my issue report from earlier on this same topic #160

I posted in the discord and was referred here, but your other post seems to mirror exactly my use-case and request more than this.

I'm glad to know I'm not alone in this, but it didn't seem as well received as I had hoped. Perhaps that has changed with time. We will see.

**Comment by removinggoose** [comment]
would also love this. Perhaps being able to specify filetypes to allow

**Comment by zakkarry** [comment]
can be addressed with partial matchmode in upcoming v6
