### ISSUE TITLE
Unable to install on M1 Mac

### ISSUE THREAD

**Issue by newadventure079** [cross-seed/cross-seed#360]
I ran `sudo npm install -g cross-seed` and it fails with the attached log.  It seems to be related to `better-sqlite3`
[log.log](https://github.com/cross-seed/cross-seed/files/10442261/log.log)

**Comment by mmgoodnow** [comment]
So it sounds like there are two issues here
- better-sqlite3 issue on master - fixed in #341 
- npm link doesn't work in next branch

As for the second problem - make sure you're running `npm run build` after switching branches. That means 
```shell
git checkout next
npm install
npm run build
npm link
```
