### ISSUE TITLE
includeEpisodes: false seems to be enumerating over single episodes

### ISSUE THREAD

**Issue by newadventure079** [cross-seed/cross-seed#361]
In the config file, I have `includeEpisodes: false` but looking at the verbose output, it looks like it's enumerating over single episodes. Shouldn't these single episodes be ignored? I also have `searchAll: false` too.

```
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E10.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E09.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E08.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E07.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E06.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E04.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E03.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E02.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
verbose: [decide] Narcos.Mexico.S02.2160p.NF.WEBRip.DDP5.1.x265-NTb - no match for alpharatio torrent Narcos.Mexico.S01E01.1080p.WEBRip.X264-DEFLATE - its size does not match (cached)
```

**Comment by mmgoodnow** [comment]
> I also have `searchAll: false` too.
btw, this is gone in v4, new flag is [`includeNonVideos` ](https://www.cross-seed.org/docs/tutorials/v4-migration-guide)

**Comment by mmgoodnow** [comment]
as for your question, i mean, it's getting rejected either way. either by not being the same media type, or by having a different size. So I don't think your suggestion would be materially different, if that makes sense.

Gonna close this, but please feel free to clarify if I misunderstood!

**Comment by mmgoodnow** [comment]
what do you mean by enumerating over? the logs here say:
- we queried AR for a pack, and got a bunch of single-episode results back (AR's search is a little loose, evidently).
- We have to rule these single-episode results out somehow. 
- The first check we perform is a size check - we have access to this before we snatch the torrent, so if the size check fails, no harm done. Alternatively we could perform a regex test on them but I think that'd actually be slower than the size check (regex tests are significantly more expensive than number comparison).
