### ISSUE TITLE
error: request to http://qbittorrent:8080/api/v2/torrents/properties failed, reason: socket hang up

### ISSUE THREAD

**Issue by KyleSanderson** [cross-seed/cross-seed#366]

**Comment by bakerboy448** [comment]
Not likely a bug..?

your qbittorrent instance did not respond after the timeout

https://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean

**Comment by KyleSanderson** [comment]
https://github.com/autobrr/go-qbittorrent/pull/3 it's easily fixable, and common behaviour with qBittorrent.

**Comment by bakerboy448** [comment]
> [autobrr/go-qbittorrent#3](https://github.com/autobrr/go-qbittorrent/pull/3) it's easily fixable, and common behaviour with qBittorrent.

TL;DR of the high level fix?

**Comment by mmgoodnow** [comment]
> common behaviour with qBittorrent.

what is the common behavior here, restarting? or not responding to requests while it's running?

**Comment by KyleSanderson** [comment]
> > common behaviour with qBittorrent.
> 
> what is the common behavior here, restarting? or not responding to requests while it's running?

Both, unfortunately. Responses from my experience can take upwards of 90s, and sometimes require multiple attempts. Usually if another client is waiting for a response they're queued.
