### ISSUE TITLE
qBittorrent directory 'BT_backup' is invalid

### ISSUE THREAD

**Issue by NoahBK** [cross-seed/cross-seed#368]
I am running through editing the config file and every time that I run the command for search I continually get the error "Torrent dir qBittorrentBT_backup is invalid". I have the latest version of node installed. I will put some screenshots below and I will put my full config (with private info removed) down below if anyone can point me in the right direction to help fix this issue for me.

1. [Screenshot of directory in config file](https://i.imgur.com/c3eDNhU.png)
2. [Screenshot of command line](https://i.imgur.com/1BSRsVR.png)
3. [Pastebin of my config file](https://pastebin.com/td5irCBF)

**Comment by bakerboy448** [comment]
Try `C:\\`etc (I.e. `\\` instead of `\`

**Comment by NoahBK** [comment]
I appreciate the idea, but that didn't seem to fix the issue. Still giving me the same error.

**Comment by mmgoodnow** [comment]
try using forward slashes instead of backslashes

**Comment by NoahBK** [comment]
That seems to have fixed it for me. Thank you for your help.
