### ISSUE TITLE
qbittorrent login failed, reason: self signed certificate

### ISSUE THREAD

**Issue by varunpan** [cross-seed/cross-seed#369]
I setup my docker compose and setup the config as needed. When i run `docker compose up -d`. I am getting the following error, due to my qbittorrent using Https self signed certificate. Is there a way to skip SSL verification that can be added to the config?

```
error: qBittorrent login failed: request to https://192.168.1.4:8888/api/v2/auth/login failed, reason: self signed certificate
```

**Comment by bakerboy448** [comment]
Self signed untrusted certificates for internal https communication are nothing more than security theater and there's really no use case to do that.

**Comment by bakerboy448** [comment]
If your LAN is being ease-dropped on....you've already lost the game since they presumably already have local and physical access
