### ISSUE TITLE
[bug] rss won't work if trackers are more than 20

### ISSUE THREAD

**Issue by deskmonster** [cross-seed/cross-seed#374]
From https://github.com/cross-seed/cross-seed/issues/105#issuecomment-1422173227

I just found if the length of `torznab` is longer than 20, the daemon will just send an error ```info: [scheduler] rss: last run never, next run in 0ms
info: [scheduler] starting job: rss
error: Cannot read properties of undefined (reading 'signal')```
If I reduce the numebr of trackers below 20, it works as expected.

using the latest 4.4.0 docker image

**Comment by mmgoodnow** [comment]
https://github.com/cross-seed/cross-seed/blob/7486f190c2c893d4415e3fb75f12623bba896bca/src/torznab.ts#L412-L415

omg i must have been high writing this code
