### ISSUE TITLE
Irreconcilable false positive - blocklist feature?

### ISSUE THREAD

**Issue by ahatdude** [cross-seed/cross-seed#379]
Hey,
So after our chat on discord I thought I'd just add a feature request for a simple way to block certain torrents from being added or even considered as possibilities to cross-seed.
This came about after achieving the first "irreconcilable false positive", as you put it.
Here is the log for the diff:
```
$ cross-seed diff 601ccf003689a3ec51844b2b998f02c6ec168bd7.torrent bde99189a563179158baf05e9fcc3ce8de4a1740.torrent
Configuration file already exists.
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  {
    files: [
      {
+       length: 2613,
-       length: 2554,
        name: 'Flags.of.Our.Fathers.2006.BluRay.1080p.DTS-HD.MA.5.1.AVC.HYBRID.REMUX-FraMeSToR.NFO',
        path: 'Flags.of.Our.Fathers.2006.BluRay.1080p.DTS-HD.MA.5.1.AVC.HYBRID.REMUX-FraMeSToR/Flags.of.Our.Fathers.2006.BluRay.1080p.DTS-HD.MA.5.1.AVC.HYBRID.REMUX-FraMeSToR.NFO'
...
      }
    ],
+   length: 36422340563,
-   length: 36422340504,
    name: 'Flags.of.Our.Fathers.2006.BluRay.1080p.DTS-HD.MA.5.1.AVC.HYBRID.REMUX-FraMeSToR'
  }
    at diff (file:///usr/src/cross-seed/dist/diff.js:6:9)
    at Command.diffCmd (file:///usr/src/cross-seed/dist/diff.js:21:5)
    at async Command.parseAsync (/usr/src/cross-seed/node_modules/commander/lib/command.js:923:5)
    at async file:///usr/src/cross-seed/dist/cmd.js:182:1 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Object],
  expected: [Object],
  operator: 'deepStrictEqual'
}
```
I know you gave me a few solutions to bypass this, but honestly cross-seed has been working so flawlessly that I'm tempted to just leave everything as it is and hope that you can get to this eventually.

Not sure how time consuming or difficult this would be, if I may suggest a simple way of keeping an updated blocklist:
Having a "blocklist" file that we can manually edit and just add hashes into it, but not sure if that would block it at the tracker level from even being searched. Honestly, I'm sure you'll come up with a much more elegant solution.

Thanks for your time and the great program that you've created :-)

**Comment by ahatdude** [comment]
heya, I'm sure you're busy just wondering if you'd had any time to think about a possibility of a blocklist.

Thanks :-)

**Comment by zakkarry** [comment]
Just a note for anyone still waiting, this is a tentative v6 feature that is mostly completed now.
