### ISSUE TITLE
404 when downloading torrent file

### ISSUE THREAD

**Issue by adamwinn** [cross-seed/cross-seed#38]
I'm getting the error `error parsing torrent at http://172.17.0.1:9117/dl/......` in a reproducible fashion.  I would include more info but even in verbose mode, nothing else is given

**Comment by mmgoodnow** [comment]
These are frequently rate-limiting errors. I'll try to make a code change to surface more information out of those errors but it means that the jackett dl link did not resolve to a torrent file and there's not really anything that cross-seed will be able to do to fix it.

**Comment by adamwinn** [comment]
This one wasn't a rate limiting error as it happened on my very first run of cross-seed.  Subsequent runs after that were several minutes apart.

**Comment by mmgoodnow** [comment]
Have you tried opening the link in your browser?

**Comment by adamwinn** [comment]
The link points to my internal IP address inside of docker where Jackett runs but I'll make some changes and see

**Comment by adamwinn** [comment]
The link returns 404 so that's why it was unable to be parsed.  It's odd tho because I did more testing and it's only happening on that one tracker and only via Jackett

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/releases/tag/v1.10.4

**Comment by adamwinn** [comment]
That 404 issue was because it looks like the tracker is putting up a captcha challenge and Jackett couldn't solve it.  

`Challenge detected but FlareSolverr is not configured`

**Comment by craigjmidwinter** [comment]
Sorry to bump a closed issue. I seem to be seeing this a ton as well. Other jackett consumers don't seem to have an issue and when I paste the link in a browser it does seem to work. I do have FlareSolverr configured. I'll try investigating this a bit more this weekend

**Comment by mmgoodnow** [comment]
Are these coming from a specific tracker? All torrents on that tracker or just some?

For a link that errors, what happens when you do `curl -v`?

**Comment by craigjmidwinter** [comment]
This is happening intermittently on multiple different trackers. 

This is logs for the curl with my API key and host and IP removed
```
Trying MY_IP...
* TCP_NODELAY set
* Connected to MY_DOMAIN (MY_IP) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=MY_DOMAIN
*  start date: Jan 10 07:15:43 2021 GMT
*  expire date: Apr 10 07:15:43 2021 GMT
*  subjectAltName: host "MY_DOMAIN" matched cert's "MY_DOMAIN"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x55fde8dec600)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET /jackett/dl/hdtorrents/?jackett_apikey=MY_API_KEY HTTP/2
> Host: MY_DOMAIN
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 404 
< server: nginx/1.18.0
< date: Fri, 26 Feb 2021 22:27:46 GMT
< content-length: 0
< cache-control: no-store,no-cache
< pragma: no-cache
< 
* Connection #0 to host MY_DOMAIN left intact
```

**Comment by mmgoodnow** [comment]
As you might have seen, that link 404ed for curl. Does that one work in the browser?

**Comment by craigjmidwinter** [comment]
yeah, the link works in browser for me, but the machine that jackett is running on is located elsewhere. I thought maybe it had to do with my nginx proxy which is my ingress to the docker network on that machine, but when I expose the port directly and update the config, I get the same behaviour

**Comment by craigjmidwinter** [comment]
Actually, that curl was wrong. I should have put that url in quotes I think

**Comment by craigjmidwinter** [comment]
```
midwinter@server:~$ curl -v "http://MY_DOMAIN:9117/jackett/dl/iptorrents/?jackett_apikey=MY_API_KEY&path=Q2ZESjhBSEthNlh4VVd4SWlXRUgtVThJcGFJWFVNVG05QmdnNURQWW83ZWFKOXd0WlBDTEZ0QXB4a0hja3Jtam9uOVI0aERVMG5ZSzI1RkN3OU5tNUU4TjFMVXVXVkFkbTlWcXZRd2s2RWs5UFBJV3NHY08zdUsxRHhXUVBOdjh0a0Jvd3VzTFc1MkQ1VnBhazFLbFpmLUExWFdVb0ZHSzhMeXhTNVJ3Z3ZkN096WTBhbGFhdzMtRTFISzB3NmdGTDdGTkJqMHYxU0dIUmd3SWNGdlRCMVZWMTQ1Q29kNWNGYzVlUFV2Q2gyQ2ZLMkdtbENVLXlUS3J5X2JwTGJ2V0ljLUFjQQ&file=Watch+What+Happens+Live+2021+02+23+1080p+WEB+h264-BAE"
*   Trying MY_IP...
* TCP_NODELAY set
* Connected to MY_DOMAIN (MY_IP) port 9117 (#0)
> GET /jackett/dl/iptorrents/?jackett_apikey=MY_API_KEY&path=Q2ZESjhBSEthNlh4VVd4SWlXRUgtVThJcGFJWFVNVG05QmdnNURQWW83ZWFKOXd0WlBDTEZ0QXB4a0hja3Jtam9uOVI0aERVMG5ZSzI1RkN3OU5tNUU4TjFMVXVXVkFkbTlWcXZRd2s2RWs5UFBJV3NHY08zdUsxRHhXUVBOdjh0a0Jvd3VzTFc1MkQ1VnBhazFLbFpmLUExWFdVb0ZHSzhMeXhTNVJ3Z3ZkN096WTBhbGFhdzMtRTFISzB3NmdGTDdGTkJqMHYxU0dIUmd3SWNGdlRCMVZWMTQ1Q29kNWNGYzVlUFV2Q2gyQ2ZLMkdtbENVLXlUS3J5X2JwTGJ2V0ljLUFjQQ&file=Watch+What+Happens+Live+2021+02+23+1080p+WEB+h264-BAE HTTP/1.1
> Host: MY_DOMAIN:9117
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 26 Feb 2021 23:05:18 GMT
< Content-Type: application/x-bittorrent
< Server: Kestrel
< Content-Length: 2698
< Cache-Control: no-store,no-cache
< Pragma: no-cache
< Content-Disposition: attachment; filename="Watch What Happens Live 2021 02 23 1080p WEB h264-BAE.torrent"; filename*=UTF-8''Watch%20What%20Happens%20Live%202021%2002%2023%201080p%20WEB%20h264-BAE.torrent
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 2698)
* stopped the pause stream!
* Closing connection 0

```
So it does 200 here

**Comment by craigjmidwinter** [comment]
Weird. I added an option for a `--max-parse-retries` that reattempts the parsing up to 3 times and it fixes the issue for me when I use that branch

**Comment by mmgoodnow** [comment]
I just pushed a new release, [`v2.0.1`](https://github.com/mmgoodnow/cross-seed/releases/tag/v2.0.1) which has significantly better logging for this error. If you run cross-seed with `-v` it will log a bunch of debug information when it hits this error which might be able to help.

**Comment by mmgoodnow** [comment]
@craigjmidwinter I'm gonna close this one out. Please let me know if you see any more errors that aren't rate limiting that you think can be fixed.

**Comment by newadventure079** [comment]
I see this consistently with PHD.  My guess is that it is captcha related

**Comment by newadventure079** [comment]
I went to re-add PHD in Jackett and I saw `You have to check 'Enable RSS Feed' in 'My Account', without this configuration the torrent download does not work.`

I did not have `Enable RSS Feed` enabled in my account.  I enabled it and the files download now.

Looking at the Jackett logs, I saw `Challenge detected but FlareSolverr is not configured`, so I thought it was captcha related
