### ISSUE TITLE
error: could not find a torrent with the criteria

### ISSUE THREAD

**Issue by Nemoljy** [cross-seed/cross-seed#383]
Hi, I followed the tutorial and setup Daemon Mode by running cross-seed on Docker.
But when a torrent finished, the log print error like this :

![image](https://user-images.githubusercontent.com/32947114/222969734-56f9af5e-46fc-4691-a6af-82b4c825c922.png)

qbittorrent version: v4.4.2
docker image version:latest
system: DSM 6.2.3-25423

How can I fix this?
thx for helping!

**Comment by BaukeZwart** [comment]
I have much better results searching for `infoHash` instead of `name`

**Comment by mmgoodnow** [comment]
do you use Subfolder content layout?

**Comment by Nemoljy** [comment]
> I have much better results searching for `infoHash` instead of `name`

In tutorial, 'infoHash' only for Transmission. Can it work on qBittorrent? 
Should I write something like :
`curl -XPOST http://localhost:2468/api/webhook --data-urlencode "infoHash =%I"`
or
`curl -XPOST http://localhost:2468/api/webhook --data-urlencode "infoHash =%J"`
?

There are two params in qb for `infoHash`：%I for infoHash v1, %J for infoHash v2.

**Comment by Nemoljy** [comment]
> do you use Subfolder content layout?

Yes! I need Subfolder. What should I do?

**Comment by mmgoodnow** [comment]
It'll work in qbit, use infohas v1
