### ISSUE TITLE
Feature Request: Add ability to search only on new tracker when tracker is added

### ISSUE THREAD

**Issue by balpokey** [cross-seed/cross-seed#398]
Requesting for the ability to search all torrents on a new tracker when a new tracker is added in the config. I think it would be best to also have it set as a boolean in the config.

This way when we join a new tracker we can start cross-seeding much easier. Currently, when I join a new tracker, I just delete the .db file and let it search all trackers when I add a new one. But with this feature we can greatly reduce the load put on the trackers and potentially decrease the search time.

**Comment by mmgoodnow** [comment]
this is already supported in v4.4. Just add the tracker and turn down excludeRecentSearch
