### ISSUE TITLE
Searching 0 indexers for [torrent name]

### ISSUE THREAD

**Issue by HailAlistair** [cross-seed/cross-seed#401]
I have encountered a strange issue: cross-seed search runs normally for a while, then "Searching 1 indexers for [torrent name]" becomes "Searching 0 indexers for [torrent name]", and it doesn't seem to recover until I run it again. (I don't think that any matches are being found when this is happening).

Any idea what this might be? Is there a way to read a log? Possibly a DEBUG log?

**Comment by mmgoodnow** [comment]
this is usually because an indexer is either down, or the torrent was already searched on that indexer.

**Comment by HailAlistair** [comment]
> this is usually because an indexer is either down, or the torrent was already searched on that indexer.

It seems that my PC or the router was having internet connection issues. After rebooting both, I managed to check almost 7000 torrents. 17 matches, which is around what I was expecting.

Thank you for those matches!

Is there a way to recheck already searched torrents?
So there are no debug logs for cross-seeds?
