### ISSUE TITLE
revisit entries when torznab endpoint is down

### ISSUE THREAD

**Issue by KyleSanderson** [cross-seed/cross-seed#402]
```
info: [torznab] Searching 1 indexers for Doppelhaushaelfte.S01.German
warn: Failed to reach http://jackett.jackett:9117/api/v2.0/indexers/core/results/torznab/api
info: [1952/4582] Searching for Tell.Me.Something.S01.1080p.WEB-DL.DDP5.1.H.264-N3RV0US
info: [torznab] Searching 1 indexers for Tell.Me.Something.S01.1080p.WEB-DL.DDP5.1.H.264-N3RV0US
warn: Failed to reach http://jackett.jackett:9117/api/v2.0/indexers/core/results/torznab/api
```

It's hours/days of work to have it scan again. A feature to append the search in the queue as opposed to skipping them when the torznab provider is down would be helpful.

**Comment by mmgoodnow** [comment]
The codebase is not really set up for this, but I'm planning to change the architecture to be event-based at some point, which should make this kind of thing a lot easier

**Comment by mindset-tk** [comment]
fyi @KyleSanderson that pull request should partially resolve your issue. You will have to run search again instead of appending, but on the second search it will only search indexers that haven't been searched within the search timeout you've set - assuming you've set one.

**Comment by KyleSanderson** [comment]
Thank you for letting me know.
