### ISSUE TITLE
Music Tracker

### ISSUE THREAD

**Issue by screwfaze** [cross-seed/cross-seed#407]
Is there support for music trackers such as Red and Ops? Would love to cross seed on those but the search does not seem to find anything.

Thanks

**Comment by Julianwan** [comment]
ops works but i get lots of errors with red and needed to turn it off

**Comment by ctulloch137** [comment]
I'm not on RED so there might be alot of cross-seed possibilities between RED and OPS, but outside of those 2 it doesn't seem like it.  Even just searching for music, Ops always has stuff that's completely different from public trackers, I don't think cross-seed would really help.  Naming/file tree differences alone would make cross-seed limited in use, but I almost never see the same data between Ops and public trackers too - file sizes always different.  Even if they had the same source like HDTracks lol. 
 With movies/tv, its totally different.  Besides the same exact releases being on multiple private trackers, youll often see them on public trackers too.

Just my 2 cents.

**Comment by sentriz** [comment]
fwiw i use cross-seed with red and ops, it has found at least 500 matches between the two

**Comment by zakkarry** [comment]
functions with includeNonVideos. Closing issue.
