### ISSUE TITLE
'too many SQL variables' when running in deamon mode 

### ISSUE THREAD

**Issue by addeboiii** [cross-seed/cross-seed#411]
I have a docker container running cross-seed in daemon mode. Download client is qbittorrent with ~70 000 files in the BT_backup directory. The client has ~35 000 active torrents.

After a while the docker keeps looping a message, see example below, "too many SQL variables" and I guess it is because of the large number of files. If I switch over to manual search there are no issues.

Is this something that could be fixed or does the client just have too many torrents for the daemon to handle?

`/ffbc210ddf93531ccf48d5ca95580b537d1d04de.torrent', '/torrents/ffbe5900d30c1720c5ec9d9f741aa5ffd19e0eb0.torrent', '/torrents/ffbec98f100eddfed34b933241beee30e411420c.torrent', '/torrents/ffc410d11c112b20801fc5f99c64fa1d2fce510c.torrent', '/torrents/ffc48236d7a12bb316f7598521bb8a90dbb12ba3.torrent', '/torrents/ffc6c403b1e4ce87da034a4b43471d9c7a7e4c33.torrent', '/torrents/ffc8618861330e74924720a1b1840f4d52fd9c2e.torrent', '/torrents/ffca15a21e9f72c02600ffed6dd1210fb518878a.torrent', '/torrents/ffcb647b17095c349d3e25490897372cb4f923a1.torrent', '/torrents/ffce08e416fe77ea12430ef4fe83fa088f0abd39.torrent', '/torrents/ffd1e74158e3e33474ea46561ce91a5d9fac3236.torrent', '/torrents/ffd3cb4dbe1a5891348b06c3bd5fe7f14b17fbda.torrent', '/torrents/ffd4f40648913afe94bd40cd080328d1965b2162.torrent', '/torrents/ffd4fa118631a02f7e10f3102233bebcefe36f4e.torrent', '/torrents/ffd5f92742ecdbce9579d13bb2798875663ae893.torrent', '/torrents/ffd7fc17e2dcd8feba16266656fecefda4d5570d.torrent', '/torrents/ffd808b7e1178a6bd4b966b65aa2372f97395729.torrent', '/torrents/ffd81a6c3fbe9f3eadcfce3025361fc27673213f.torrent', '/torrents/ffde5cae25dab990ce82cac4e9cca390971e3cab.torrent', '/torrents/ffe4133098a86d381ea8a1efcc71d41f8d24a3a0.torrent', '/torrents/ffe6ae99856c06dc2ee3eb66fe2a290799623e53.torrent', '/torrents/ffe717ad6b96e072b1f18b05b742184d371468e9.torrent', '/torrents/ffe920ccca8c031f748ceeeae935ea2444dd5d37.torrent', '/torrents/ffe9a035988b544d81148e448c3762c238e98c92.torrent', '/torrents/ffeb178e6a90a8c43a1dacc4c804cc9e3428ffe0.torrent', '/torrents/ffeb7807b6e02ee72e84881e316e42058b196370.torrent', '/torrents/ffebc1a09286ba2f39cd5886b0cb146e8c6cd455.torrent', '/torrents/ffec4d7ea6091bfc5777a2fe2908cb8109e9ee02.torrent', '/torrents/ffed0c73a90f9debc1847fdeb9c656ec0cf74e24.torrent', '/torrents/fff0c5124f35ebd013590d31b777704bcb758dee.torrent', '/torrents/fff2aeb78beb3931ea3e93b41ed3a455a2ecfd96.torrent', '/torrents/fffa9762c9066cc1d884388ce6641c9919d70679.torrent', '/torrents/fffb6bb110376ca5699ec2f487fea7e0995d9a1f.torrent', '/torrents/fffc3480eedd4eb4a9c40e513862e50adfa8e7fa.torrent', '/torrents/fffd331356f01121de3c91a38c064facbb100aff.torrent', '/torrents/fffe59d592b76c08727c8e0d263a90f4fc600e95.torrent') - too many SQL variables`

**Comment by zakkarry** [comment]
This appears to be a limitation of the SQL command or library, rather than anything in cross-seed. I'm not sure sqlite is built to accept an insert of 75000 variables.

I'd recommend trying to split up your qbittorrent and multiple cross-seed instances, this might yield more manageable seed counts for the database.

**Comment by mmgoodnow** [comment]
this is probably a fixable bug

**Comment by mmgoodnow** [comment]
https://github.com/cross-seed/cross-seed/blob/eb201b70838b8c6fb854d87f479876b706cb2956/src/torrent.ts#L162-L162

might be coming from here

**Comment by SnippetSpace** [comment]
Same issue encountered on v6 with 33K torrents in qbittorrent. I'm not sure what the hard limit is. Did not have the issue with v5 with around 26K torrents so it's likely somewhere in between those values.

**Comment by mmgoodnow** [comment]
after doing some thinking, easiest solution is likely to add `dirContents` to a temporary table and then use that for the NOT IN clause

**Comment by SnippetSpace** [comment]
After deleting 5K torrents in July I'm already back to 33K torrents 💀. A permanent fix for this would be appreciated.

**Comment by mmgoodnow** [comment]
fixed in https://github.com/cross-seed/cross-seed/releases/tag/v6.0.0-39 (prerelease)
