### ISSUE TITLE
cross-seed changing tier value for the announce urls?

### ISSUE THREAD

**Issue by WhereIsF1** [cross-seed/cross-seed#413]
I recently noticed that torrents which are saved & injected by cross-seed have changed tier values for the announce URLs. This behavior throws some problems on me since some trackers I use don't want these high announce rates coming with it.

Is there any way to fix this? 

Thanks!

(And yes, I know there's a setting in qBittorrent to disable announcing to all Tiers.)

**Comment by mmgoodnow** [comment]
https://github.com/webtorrent/parse-torrent/issues/152

**Comment by klepp0906** [comment]
+1 on this.  can confirm.  i made a big ole elaborate issue report on the prowlarr github assuming the "fault" was on that end and cross-seed was doing it right.  Could have saved myself the trouble had i simply added a torrent without anything in between/manually but i'm gonna blame a late night and lack of coffee this AM on that.

honestly maybe im just special.  it managed to elude my notice up until now to begin with.

**Comment by mmgoodnow** [comment]
@klepp0906 @WhereIsF1 mind testing this pr out?

**Comment by klepp0906** [comment]
> @klepp0906 @WhereIsF1 mind testing this pr out? you can use the `pr-445` docker tag

unfortunately im a windows user so no docker here.  just been installing via npm.  if theres a way to designate via that, then sure.  otherwise will have to rely on @WhereIsF1

**Comment by mmgoodnow** [comment]
for npm:
```
git clone https://github.com/cross-seed/cross-seed
cd cross-seed
git branch mg-vendor-parse-torrentt # yes the branch has a typo in it
npm install
npm link
npm link cross-seed
...
cross-seed search …
```

**Comment by klepp0906** [comment]
how will that behave if i have an existing install?  overwrite/update it? do i need to use -g since the current npm build is installed with it?

**Comment by mmgoodnow** [comment]
those commands will override the version already installed by npm - to put the old one back, you can use `npm unlink cross-seed` and `npm unlink` from inside the repo's root directory, but I don't remember which order.

**Comment by mmgoodnow** [comment]
@klepp0906 have you gotten a chance to test it out? any bugs?

**Comment by klepp0906** [comment]
sorry. been a really buuuusy week.  huge job and family in from out of town.  would have forgotten had you not commented but nothing untoward thus far
