### ISSUE TITLE
Webhook fails when content layout is not original when using name based search

### ISSUE THREAD

**Issue by buthed010203** [cross-seed/cross-seed#425]
When set to create subdirectory, qbt will end up sending `some_file` as the name when cross-seed expects `some_file.txt` which causes it to not perform a match. ~~Question: Why does the webhook use name instead of hash anyways?~~ *Apparently it does support it*

**Comment by mmgoodnow** [comment]
this is because qBittorrent sends the wrong value for `name`. 

resolution: use info hash
