### ISSUE TITLE
How to check if cross-seed is working 

### ISSUE THREAD

**Issue by fishredleung** [cross-seed/cross-seed#427]
Got set up in docker by following the tutorial. The program is running in daemon mode but I found that the there were not much upload  in my torrents. I'm currently using qBittorrent client, how can I check if cross-seed is working and inject the other private trackers in to my finished downloads?

**Comment by fishredleung** [comment]
got it working correctly now

**Comment by xiNeRoar** [comment]
how to check if it is running? can you specify how?
