### ISSUE TITLE
excludeRecentSearch API usage is too bursty

### ISSUE THREAD

**Issue by Terebi42** [cross-seed/cross-seed#432]
When doing the initial search against torrents or data, everything will have the same search date.  Therefore when excludeRecentSearch is used, all torrents/data will be available for search again at the same time. This will lead to feast vs famine use of API. 

Add a random amount of time based on the excludeRecent duration (for example, if exclude recent is 14 days,  add +/- 7 days to each torrent randomly, to spread them out)

This would also enable more frequent searches (hourly? 2x a day?)  since any particular search will only be hitting a small subset of the files.

**Comment by mmgoodnow** [comment]
discussed here: https://github.com/cross-seed/cross-seed/pull/418#issuecomment-1552489311
