### ISSUE TITLE
Improve movie search support

### ISSUE THREAD

**Issue by bakerboy448** [cross-seed/cross-seed#437]
- parse for tmdbid or imdbid from name or data searched and perform a Torznab movie search with the ids
- Both id and name searches should be attempted
- Improve parsing of movie titles to more clearly search the movie and year

**Comment by mmgoodnow** [comment]
I tried doing `?t=movie` when I added `?t=tvsearch` but it resulted in less matches than `?t=search`. I could try again though. Are there other benefits to searching with `?t=movie` over `?t=search`?

Where do you suggest we find these tmdb/imdb ids? Using their apis?

**Comment by bakerboy448** [comment]
imdbid / tmdbid / tvdbid should just tried to be parsed from the pushed title.  If it's there, great use it (and S/E for sonarr). If not use the usual title logic 

caps per tracker will indicate what search abilities are supported

**Comment by mmgoodnow** [comment]
Is it common for ids to be in the titles? Not sure I've seen this before.

> caps per tracker will indicate what search abilities are supported
yeah, but what makes movie search better than plain search?

**Comment by bakerboy448** [comment]
Starr recommended naming scheme is to include it in naming - so primary usecase would be data search of the library.

Free text search all vs. movie specific search is the high level.   Torznab spec docs should have some more details
