### ISSUE TITLE
Allow using disabled prowlarr indexers

### ISSUE THREAD

**Issue by pelican12383** [cross-seed/cross-seed#440]
I think it would be very helpful if there was an option to allow using prowlarr indexers that are disabled.

I like to keep certain indexers in prowlarr disabled, so that automated clients (sonarr/radarr/etc.) won't negatively affect my ratio for these specific indexers. At the same time, I would like to cross-seed to/from these disabled indexers.

Currently, if an indexer is disabled in prowlarr, I get the following warning in cross-seed:
`warn: Ignoring indexer that doesn't support searching`
_(I'm assuming this is behavior expected for disabled indexers?)_

Even if I enable that indexer in prowlar, and then try cross-seed again, I still get the same error. I need to wipe out cross-seed.db to get cross-seed to start using the indexer again.

As a workaround, if I enable the indexer from the start, run cross-seed once, and then disable the indexer afterwards, cross-seed will continue using the disabled indexer.

Thanks!

**Comment by bakerboy448** [comment]
This doesn't make sense and is not possible. There is nothing at all xseed can do for a disabled indexer in prowlarr as prowlarr correctly responds with no valid search caps etc 

disabled indexers in prowlarr are disabled and cannot be used at all. No prowlarr plans to ever change that.

there's also no reason to disable indexers in prowlarr to avoid them being used in Starrs nor does that make sense....simply configure your app sync profile correctly..sound like you just need to have a sync profile that's does not allow rss or automatic grabs and interactive only.

alternatively use tags to prevent those indexers from even syncing to any app

**Comment by pelican12383** [comment]
> simply configure your app sync profile correctly..sound like you just need to have a sync profile that's does not allow rss or automatic grabs and interactive only.

Thank you! Properly setting up the sync profiles solved everything for me. I had misunderstood what the sync profile was used for.

Also, I double-checked the workaround I mentioned, and this was incorrect, like you pointed out: cross-seed will not work with a enabled->disabled indexer. That `Ignoring indexer that doesn't support searching` warning does in fact go away, but the indexer will return no results.
