### ISSUE TITLE
Search Limit shouldn't include 0 indexer searches

### ISSUE THREAD

**Issue by removinggoose** [cross-seed/cross-seed#453]
Hi, I have not been able to properly utilise the search limit as every time a search occurs, it searches for the limit amount (let's say 100) and if the first 100 were already searched for in the past day, it still includes them in the 100 searches. This means that all of the 100 torrents are taken up by items that searched 0 indexers and therefore no actual searches occurred. It would be useful if any item that searches 0 indexers, be excluded from the search limitations.

**Comment by removinggoose** [comment]
any help on this please?

**Comment by diligent-platypus** [comment]
I'm running into the same issue. I've set the `searchLimit=10`, `searchCadence=5min` and `excludeRecentSearch=1w` but it continuously checks the first 10 which, after the first run, are filtered by timestamp.

Any input on this would be appreciated

**Comment by removinggoose** [comment]
> I'm running into the same issue. I've set the `searchLimit=10`, `searchCadence=5min` and `excludeRecentSearch=1w` but it continuously checks the first 10 which, after the first run, are filtered by timestamp.
> 
> Any input on this would be appreciated

Perhaps you could also post your config (minus sensitive info). Then it's already here when/if someone gets around to looking at this.

**Comment by removinggoose** [comment]
any update or info on this please?

**Comment by mmgoodnow** [comment]
No updates

**Comment by mindset-tk** [comment]
Hello. I believe I've fixed this issue with some simple tweaks in the PR I opened earlier today. Thank you for your consideration.
