### ISSUE TITLE
Qbittorrent - the info hash matches a torrent you already have

### ISSUE THREAD

**Issue by zorvok** [cross-seed/cross-seed#454]
Almost every torrent on TD and IPT uses the same hash.  So can't use cross seed in daemon without having that error on every single torrent.   I've found a few work arounds but it really messes with my automation mindset:

1.  Tell cross seed to send to a different torrent client, manually scan my torrent download folders using --data-dir.
2.  or edit the decide.ts and delete out the few lines that tell cross-seed what to do with matching hashs, than manually run search.

option 1 is tedious because I have to run the manual search command multiple times to ensure each category of torrents goes to the right folder.
option 2 doesn't affect the currently running daemon.  and of course, I have to completely redo it if I need to restart the docker for whatever reason.

Is it possible to add something in the config to skip hash checking?

**Comment by zorvok** [comment]
Decided to run two instance of cross-seed in  VM's on alpine-linux.  Set up cron jobs to run seach commands with different variables depending on what category folder it's looking at.  It's doing what I need for now this way.

I've thought about it and the only way I can see an easy work around that's seemless, is if and when multiple torrent clients are supported.  Give us the ability to say if the matching hash is from tracker A send to client A, if from Tracker B send to Tracker B, and than let the client handle the rejection if it already exists in the client.

**Comment by mmgoodnow** [comment]
Are you able to even load multiple torrents with the same info hash into qbittorrent? does it just treat it as a single torrent with extra announce urls? this seems like it would lead to ratio cheating

**Comment by zorvok** [comment]
Not able to.  Tried that a few different ways.   So have to utilize two qbittorrent instances with the two cross-seed instances.
