### ISSUE TITLE
[Request] handling subfolder search for torrent files under /torrents

### ISSUE THREAD

**Issue by OrpheeGT** [cross-seed/cross-seed#458]
Hello,

I would like to use "Synology Download Station" 
Currently using rtorrent, and cross-seed works perfect with it.

But with Download Station, it seems it create a sub folder for each torrent file added...

![image](https://github.com/cross-seed/cross-seed/assets/8038551/9d3e5051-b7e3-491c-a25d-08c8ebf476a9)

I tried set /torrents to match download station main folder.
            `- /volume1/@download:/torrents:ro`
![image](https://github.com/cross-seed/cross-seed/assets/8038551/3e67bde5-abd8-46cc-bb6c-70b259b1499f)

But no torrents where found.
I changed to one of the subfolders to confirm like 
            `- /volume1/@download/4:/torrents:ro`
![image](https://github.com/cross-seed/cross-seed/assets/8038551/1207e578-e12a-4491-bf28-2d7304c75c46)

Would it be possible to add an option to parse every subfolders inside /torrents ?
(Probably only direct subfolder... not every sub-sub-n-folders)

Thanks

**Comment by OrpheeGT** [comment]
Could some regex like this be implemented ? :

^\/torrents\/([0-9][0-9]{0,3}|10000)\/

**Comment by mmgoodnow** [comment]
I can't really handle all of the configuration complexity for everyone's unique use cases at the moment. I would recommend forking
