### ISSUE TITLE
Log level?

### ISSUE THREAD

**Issue by Schaka** [cross-seed/cross-seed#462]
Sorry for creating an issue, I both went through the code and all previous issues to see if there was any information.
I'd like to change the log level for cross-seed (running in Docker). 

Currently, I see the log statements below a lot, with the occasional error thrown in. I'd like to be able to tell WHY this is happening. The very same config works just fine on my home server - but on the seedbox it's struggling. 
```
warn: Failed to reach http://prowlarr:9696/1/api
warn: Failed to reach http://prowlarr:9696/2/api
warn: Failed to reach http://prowlarr:9696/3/api
warn: Failed to reach http://prowlarr:9696/4/api
```

How do I set the log level? I saw there's more debug logging specifically for those errors.

**Comment by bakerboy448** [comment]
3 log files are created
Look at the log files not the console logs
