### ISSUE TITLE
Transmission RPC URL credentials not decoded before transfer to Authorization header

### ISSUE THREAD

**Issue by Omar007** [cross-seed/cross-seed#463]
The credentials that may be present in the Transmission RPC URL (config or command-line flag) are not decoded before they are base64 encoded and put into the `Authorization` header. This results in a 401 response from Transmission when the username and/or password contains characters that require URL encoding to be applied: https://github.com/cross-seed/cross-seed/blob/c538e38ca3329274f1061a593352bda10b619e2d/src/clients/Transmission.ts#L59  

This problem does not seem to be present in the other clients, these all perform a call to `decodeURIComponent` before passing the information on into the relevant API requests.  

(small side-request; log the response code when an error is returned? https://github.com/cross-seed/cross-seed/blob/c538e38ca3329274f1061a593352bda10b619e2d/src/clients/Transmission.ts#L101)

**Comment by zakkarry** [comment]
Just as a note, this behavior is also present in the qbittorrentUrl and I'd assume rTorrent's implementation too.

**Comment by Omar007** [comment]
It is. But:

> This problem does not seem to be present in the other clients, these all perform a call to decodeURIComponent before passing the information on into the relevant API requests.

For some reason it's just not being done for Transmission.

**Comment by zakkarry** [comment]
I've had multiple people with special characters in their qbit password tell me they cant connect, and changinf to an alphanumeric password fixed it...

This was within the last few weeks. I'll double check this later, as it wasn't my personal instance or setup... but I assume this is the case.

**Comment by mmgoodnow** [comment]
> these all perform a call to decodeURIComponent before passing the information on into the relevant API requests. For some reason it's just not being done for Transmission.

This sounds like it was just an oversight - we should be able to fix easily
