### ISSUE TITLE
qBittorrent SQLite database support

### ISSUE THREAD

**Issue by onedr0p** [cross-seed/cross-seed#467]
It would be nice if cross-seed was supported when using sqlite with qbittorrent.

_Previous issue (https://github.com/cross-seed/cross-seed/issues/365) got a bit out of hand, so I am re-opening this feature request._

**Comment by anthr76** [comment]
I would also greatly be interested in this!

**Comment by buroa** [comment]
Same here!

**Comment by mouzzampk2014** [comment]
This one will definitely help and now 4.3.9 seems like very old.

**Comment by mmgoodnow** [comment]
I reopened #365
