### ISSUE TITLE
check to make sure that dataDirs is an array and not a string

### ISSUE THREAD

**Issue by mmgoodnow** [cross-seed/cross-seed#475]
I think the current behavior is that if you specify dataDirs as "hello", it'll try to split it into `["h", "e", "l" ,"l", "o"]` and then silently find no contents (no wonder)

**Comment by zakkarry** [comment]
`fallback(Array.isArray(fileConfig.dataDirs) ? fileConfig.dataDirs : [fileConfig.dataDirs])`

Would potentially mitigate single directory not being in an array, however it would freak out if there were two. 

Not sure if this is a complete solution given how the config is parsed.

**Comment by zakkarry** [comment]
I've already merged a fix for this to the next version branch. It's currently not in a testing/beta state from my perspective, but it has been addressed.
