### ISSUE TITLE
Issue: Invalid XML fetching caps

### ISSUE THREAD

**Issue by flos06** [cross-seed/cross-seed#477]
Hi I'm running into an issue. I'm running it direct and not through docker.
I've disabled authentication on prowlarr for now because with it enabled I cant get through auth even though I've used http://USER:PASS@127.0.0.1:9696/prowlarr/3/api?apikey=REMOVED

So with auth disabled the command I'm running:

cross-seed search --torrent-dir ~/.local/share/data/qBittorrent/BT_backup --output-dir . --torznab http://127.0.0.1:9696/prowlarr/3/api?apikey=REMOVED

Response:

info: Validating your configuration...
error: Indexer http://127.0.0.1:9696/prowlarr/3/api responded with invalid XML when fetching caps, check verbose logs
error: no working indexers available

I am kind of new so I'm unsure where I can even find these verbose logs. Prowlarrs logs dont say anything is wrong but they aren't very useful either.

Any ideas?

**Comment by flos06** [comment]
Figured out verbose was as simple as adding --verbose 👍 
verbose: [configdump] {
  matchMode: 'safe',
  dataCategory: 'cross-seed-data',
  linkType: 'symlink',
  skipRecheck: false,
  maxDataDepth: 2,
  includeNonVideos: false,
  includeEpisodes: false,
  fuzzySizeThreshold: 0.02,
  verbose: true,
  action: 'save',
  delay: 10,
  snatchTimeout: 30000,
  searchTimeout: 30000,
  searchLimit: 0,
  torrentDir: '/home/flos/.local/share/data/qBittorrent/BT_backup',
  outputDir: '.',
  torznab: [
    'http://127.0.0.1:9696/prowlarr/3/api?apikey=[REDACTED]'
  ]
}
info: Validating your configuration...
error: Indexer http://127.0.0.1:9696/prowlarr/3/api responded with invalid XML w                                                                                                                                                                                                                                             hen fetching caps, check verbose logs
debug: Response body first 1000 characters: <!doctype html><html lang="en"><head                                                                                                                                                                                                                                             ><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initia                                                                                                                                                                                                                                             l-scale=1"/><meta name="mobile-web-app-capable" content="yes"/><meta name="apple                                                                                                                                                                                                                                             -mobile-web-app-capable" content="yes"/><meta name="theme-color" content="#e6600                                                                                                                                                                                                                                             1"/><meta name="msapplication-navbutton-color" content="#3a3f51"/><meta name="de                                                                                                                                                                                                                                             scription" content="Prowlarr"/><link rel="apple-touch-icon" sizes="180x180" href                                                                                                                                                                                                                                             ="/Content/Images/Icons/apple-touch-icon.png?h=6OFTjFECz9UsB7H/TlShUg"/><link re                                                                                                                                                                                                                                             l="icon" type="image/png" sizes="32x32" href="/Content/Images/Icons/favicon-32x3                                                                                                                                                                                                                                             2.png?h=lmqCw7GaBq+Sl0mzceEopQ"/><link rel="icon" type="image/png" sizes="16x16"                                                                                                                                                                                                                                              href="/Content/Images/Icons/favicon-16x16.png?h=eoRdw1mTmIIEK5L0pTH5mw"/><link                                                                                                                                                                                                                                              rel="manifest" href="/Content/Images/Icons/manifest.json?h=cMvkdTsMtUMo5Q+xA1t38                                                                                                                                                                                                                                             g" crossorigin="use-credentials"/><link rel="mask-icon" href="/Content/Images/Ic                                                                                                                                                                                                                                             ons/safari-pinned-tab.svg?h=D8kxvQdNZQhWkyStrIiagA" color="#00ccff"/><link rel="                                                                                                                                                                                                                                             shor
error: no working indexers available

**Comment by flos06** [comment]
<!doctype html><html lang="en"><head                                                                                                                                                                                                                                             ><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initia                                                                                                                                                                                                                                             l-scale=1"/><meta name="mobile-web-app-capable" content="yes"/><meta name="apple                                                                                                                                                                                                                                             -mobile-web-app-capable" content="yes"/><meta name="theme-color" content="#e6600                                                                                                                                                                                                                                             1"/><meta name="msapplication-navbutton-color" content="#3a3f51"/><meta name="de                                                                                                                                                                                                                                             scription" content="Prowlarr"/><link rel="apple-touch-icon" sizes="180x180" href                                                                                                                                                                                                                                             ="/Content/Images/Icons/apple-touch-icon.png?h=6OFTjFECz9UsB7H/TlShUg"/><link re                                                                                                                                                                                                                                             l="icon" type="image/png" sizes="32x32" href="/Content/Images/Icons/favicon-32x3                                                                                                                                                                                                                                             2.png?h=lmqCw7GaBq+Sl0mzceEopQ"/><link rel="icon" type="image/png" sizes="16x16"                                                                                                                                                                                                                                              href="/Content/Images/Icons/favicon-16x16.png?h=eoRdw1mTmIIEK5L0pTH5mw"/><link                                                                                                                                                                                                                                              rel="manifest" href="/Content/Images/Icons/manifest.json?h=cMvkdTsMtUMo5Q+xA1t38                                                                                                                                                                                                                                             g" crossorigin="use-credentials"/><link rel="mask-icon" href="/Content/Images/Ic                                                                                                                                                                                                                                             ons/safari-pinned-tab.svg?h=D8kxvQdNZQhWkyStrIiagA" color="#00ccff"/><link rel="                                                                                                                                                                                                                                             shor

**Comment by bakerboy448** [comment]
Why are the IPs different? Sounds like it's not actually on the same box on localhost?

/prowlarr is required if you have a baseurl set in prowlarr and Prowlarr's UI auth has no impact on the api

**Comment by flos06** [comment]
its all sorted. Localhost often gives me trouble not sure why. But the issue was that I thought I needed 1 prowlarr url but I needed every torznab url for each indexer. It's working as intended now. This can be closed :)

**Comment by bakerboy448** [comment]
Prowlarr also does not need basic auth for the api as in your original issue - nor should there be any additional auth on prowlarr api routes - that's the point of the apikey

**Comment by zakkarry** [comment]
Closing at OP author request.
