### ISSUE TITLE
Silent Failing when inject is misspelled.

### ISSUE THREAD

**Issue by lokiwho** [cross-seed/cross-seed#478]
When the action is typoed (in my case I did injest not inject) it silently failed and defaulted to save

```javascript
  /**
     * With "inject" you need to set up one of the below clients.
     * Options: "save", "inject"
     */
    action: "injest",
    /**
``` 
vs 

```javascript
  /**
     * With "inject" you need to set up one of the below clients.
     * Options: "save", "inject"
     */
    action: "inject",
    /**
```

**Comment by zakkarry** [comment]
this is due to the following

`				.default(fallback(fileConfig.action, Action.SAVE))`

and is expected behavior when action is defined as something erroneous.

**Comment by mmgoodnow** [comment]
Gonna reopen this because I think it's worth considering some validation for these types of things.

**Comment by zakkarry** [comment]
I was at work on my phone when I closed. After some reflection I was going to reopen as soon as I got home, just now.

I think it would be easy enough to implement...probably going to try and get it done tonight
