### ISSUE TITLE
`filtered by timestamps` for most of the torrents

### ISSUE THREAD

**Issue by rtmlp** [cross-seed/cross-seed#480]
Hi,

I am able to setup a docker container as cross seed some of the torrents but for most of the remaining ones, I see the error `filtered by timestamps`. How can I force the remaining ones to be searched. Is there any option in the config that is filtering based on timestamps?

Thanks

**Comment by bakerboy448** [comment]
- https://www.cross-seed.org/docs/reference/options#excludeolder
- https://www.cross-seed.org/docs/reference/options#excluderecentsearch

**Comment by rtmlp** [comment]
Thanks for sharing the documentation links for my question
