### ISSUE TITLE
Environment variable support

### ISSUE THREAD

**Issue by onedr0p** [cross-seed/cross-seed#486]
It would be nice if cross-seed supported env vars. It seems pretty easy to do but I am wondering what you would like to take precedence? For example, with the "new" way described below, args would take precedence and then env and then the file or the default.

## old

```js
		.option(
			"--data-category <cat>",
			"Category to assign torrents from data-based matching",
			fallback(fileConfig.dataCategory, "cross-seed-data")
		)
```

## new

```js
		.addOption(
			new Option(
				"--data-category <cat>",
				"Category to assign torrents from data-based matching"
			)
				.env("CS_DATA_CATEGORY")
				.default(fallback(fileConfig.dataCategory, "cross-seed-data"))
		)
```

It is also worth pointing out that some options might not be possible to set as an env var due to being an array or object. However I think this is fine, a mixed config file / env is pretty common in software and maybe in the future cross-seed could support all options via env.

I am willing to PR this but just wanted to get ya'll thoughts on it before I dive too far into it.

**Comment by mmgoodnow** [comment]
The configuration surface is already pretty messy, so I'm not very keen on entertaining this.

**Comment by onedr0p** [comment]
I feel that for sure which is why I didn't go ahead with the PR out of nowhere. However there is something to be said about running cross-seed in a container and having all configuration defined via env without the need for args or a file.

For example, with Kubernetes it is much easier to build out the configuration with ENV because k8s supports defining secrets objects that can be used in the env configuration of the pod. This cannot be done with args and with a file based config the entire config file needs to be stored in a secret and mounted into the pod which makes maintenance a bit harder.

**Comment by mmgoodnow** [comment]
One thing you could do is change the container entry point to read environment vars and put them into CLI args:

`cross-seed --torznab "$TORZNAB" --qbittorrentUrl "$QBIT_URL"` etc.

**Comment by onedr0p** [comment]
Yep there are workarounds for sure [like you mentioned](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments). It's not a bad idea either for now.

**Comment by onedr0p** [comment]
Good point @fabricionaweb that should work swell. I'll go ahead and close this issue as it covers my usecase. Thanks!
