### ISSUE TITLE
Why are not all torrents suitable to search for matches?

### ISSUE THREAD

**Issue by christianmerges** [cross-seed/cross-seed#490]
[search] Found 9139 torrents, 989 suitable to search for matches
I am using qbit and using the bt_backup folder as input.

What can i do to check all the torrents for cross seeds?

**Comment by bakerboy448** [comment]
Not a bug.

based on your configuration parameters torrents are excluded due to being episodes / older than / etc

**Comment by christianmerges** [comment]
ok i changed
includeEpisodes: true
includeNonVideos: true
Now:
[search] Found 9263 torrents, 8701 suitable to search for matches

i assume the difference is now, torrents, already existing for multiple trackers in the queue?

**Comment by zakkarry** [comment]
It filters based on timestamps per your relevant config options (excludeRecent...) and infohash and torrent/file name from the .torrent file or data search (tested this just now)...

optionally if you use the include settings that are based on content (includeEpisodes/includeSingleEpisods (just added option)/includeNonVideos) it will filter based on that as well.
