### ISSUE TITLE
Request: send tv shows and movies to different output dirs

### ISSUE THREAD

**Issue by sage2050** [cross-seed/cross-seed#500]
for torrent organization it would be nice to have different output directories for each type of file. This would allow users whos downloads are in separate directories to better inform their clients where to put each new cross-seed 

for example, i keep my tv shows in /downloads/_tv and movies in /downloads/_movies
I direct all new torrents in my cross-seed client to /downloads/_tv since there are more of those files, and then I have to manually move the unmatched movies to /downloads/_movies

**Comment by zakkarry** [comment]
We're using regex to match these media types, and while its mostly consistent, there are quite a few poorly named movies and tv (specifically anime and scene) that could result in no matching/identification.

Not sure how that would handled.

Ideas?

**Comment by sage2050** [comment]
You're already prepending [episode] and [movie] to the torrent files, that
can be used to sort into dirA or dirB. bad matches may happen but I think
this would be a perfectly acceptable solution. This could be further
expanded to tracker-based sorting.

**Comment by mueslo** [comment]
I have the same issue.

At least for deluge, the torrent statefile contains the directory each torrent is in ("save_path"). Why not just use that and add a configurable path mapping?

**Comment by mmgoodnow** [comment]
Deluge injection would likely solve your use case
