### ISSUE TITLE
rTorrent injection uses incorrect paths if torrent's name was not added to the original path

### ISSUE THREAD

**Issue by uraid** [cross-seed/cross-seed#502]
In rTorrent, there's an option to not use torrent's name in its path: `Don't add torrent's name to path`.
This results in `cross-seed` injecting torrents with incorrect paths, as it doesn't take that into account.

See the commands reference here: https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-directory
If the torrent has a single file, its name is not appended to `d.directory`, but if it has multiple files, the name is appended.
This is an inconsistency in the way the 'RTorrent' handler is using its API, even with the check for multiple files (`isMultiFileStr` https://github.com/cross-seed/cross-seed/blob/v5.5.1/src/clients/RTorrent.ts#L174C25-L174C39)

**Comment by mmgoodnow** [comment]
Can you show more information about your bug? I've been using rTorrent injection without base paths for years.

**Comment by uraid** [comment]
Of course.
Find one of your torrents which are a folder and not a single .mkv file, then `Save to` action, change it to a path without a name (for example, `/data/media/tv/test`), and tick the `Don't add torrent's name to path` and `Move data files`.
Now, if you use the inject, cross-seed will use an incorrect path (`/data/media/tv`) as it sees it's `isMultiFileStr`, and will do `dirname(dir)` on it.
