### ISSUE TITLE
Setting limits for seed ratio/time on cross-seeds

### ISSUE THREAD

**Issue by xiNeRoar** [cross-seed/cross-seed#505]
may i ask when a torrent is be cross-seeding, how long will it last?
is there anyway i can control the seed ratio or seed time of a cross-seeding torrent?

**Comment by zakkarry** [comment]
Your torrent client should allow for settings for this, this has nothing to do with cross-seed in its current implementation. Set either a label's seed ratio/time settings or set global ones that will apply to all torrents.

**Comment by xiNeRoar** [comment]
Thanks
