### ISSUE TITLE
Notifications not working with gotify [Bug]

### ISSUE THREAD

**Issue by spyhuntergenral** [cross-seed/cross-seed#508]
currently notifications are being sent but gotify throws 400 error when message is received,

seems like the problem is just a bit of JSON formatting: 
I'm not sure how this will effect other apprise applications but just leaving this here in case someone needs it.

changing the notify function in pushNotifier.ts to the below, and notifications start working:

	notify({ title = "cross-seed", body, ...rest }: PushNotification): void {
		if (this.url) {
			fetch(this.url, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				//body: JSON.stringify({ title, body, ...rest }),
				body: JSON.stringify({title: title, message: body, ...rest }),
			}).catch(() => {
				logger.error({ message: "Failed to send push notification" });
			});
		}
	}

config.js:
`    notificationWebhookUrl: "http://ip:port/message?token=#######",
`

**Comment by mmgoodnow** [comment]
Cross seed does not support gotify. It supports notifiarr and apprise.

**Comment by mmgoodnow** [comment]
looks like Apprise supports gotify: https://github.com/caronc/apprise/wiki/Notify_gotify
