### ISSUE TITLE
torznab human-friendly-labels

### ISSUE THREAD

**Issue by ZVeguillaCotto** [cross-seed/cross-seed#515]
In the spirit of implementing console logs that are easier and faster to read/understand.

My config looks something like this:

```
torznab: [
        "http://1.2.3.4:9696/1/api?apikey=12345",
        "http://1.2.3.4:9696/2/api?apikey=12345",
        "http://1.2.3.4:9696/3/api?apikey=12345",
        ...
                  ],
```

The output console occasionally reports:
`warn: Failed to reach http://1.2.3.4:9696/1/api`
and other similar looking outputs.

Currently, to know what tracker is being reported as having an issue I must go to Prowlarr, sort my trackers by add date, and guesstimate which one is /#/.

It would be nice if the console output looked more like this:
`warn: Failed to reach http://YourFavoriteTracker/api`
or
`warn: Failed to reach YourFavoriteTracker`

I have tried altering my config as follows:
```
torznab: [
        "http://1.2.3.4:9696/1/api?apikey=12345", //YourFavoriteTracker#1Name
        "http://1.2.3.4:9696/2/api?apikey=12345", //YourFavoriteTracker#2Name
        "http://1.2.3.4:9696/3/api?apikey=12345", //YourFavoriteTracker#3Name
        ...
                  ],
```

With this mod I can at least look at the config file and quickly reference what //Name is for tracker # without having to open Prowlarr and guess.

Could this "feature" be implemented?

**Comment by bakerboy448** [comment]
that's not Torznab spec nor a valid url.   You should be able to append &indexer=YourFavoriteIndexer to the Torznab URLs and prowlarr will ignore it
