### ISSUE TITLE
Expose different status codes for different responses

### ISSUE THREAD

**Issue by buroa** [cross-seed/cross-seed#525]
For example, say a torrent is a potential xseed but it's not done in the client yet. We should respond with a different status code vs the default 204.

**Comment by mmgoodnow** [comment]
why?

**Comment by buroa** [comment]
So we can retry these potential cross-seeds requests with other automation tools, such as autobrr. I already understand the qbit on-completed way to potentially catch it later, but why not expose these highly-valuable responses as status codes?
