### ISSUE TITLE
Unable to reach prowlarr endpoints

### ISSUE THREAD

**Issue by rtmlp** [cross-seed/cross-seed#528]
Hi,

I created a gluten container and routed the traffic from `prowlarr`, `qbittorrent` and `cross-seed` through the gluetun container using network_mode in compose file.

The tornzab urls in the cross-seed config file is something like this

```
  torznab: [
      "http://localhost:9696/1/api?apikey=key", 
      "http://localhost:9696/2/api?apikey=key"] 
      
 qbittorrentUrl: "http://user:pass@localhost:8090",
```

But I get the following warnings in the docker logs

```
warn: Failed to reach http://localhost:9696/1/api
warn: Failed to reach http://localhost:9696/2/api
```

With the same settings, `cross-seed` was able to add new (cross-seed) torrents to qbittorrent. I am not sure why the warnings are in the logs. I checked prowlarr and things are working fine when I tested the indexers

Thanks

**Comment by suineg** [comment]
```
  torznab: [
      "http://prowlarr:9696/1/api?apikey=key", 
      "http://prowlarr:9696/2/api?apikey=key"] 
      
 qbittorrentUrl: "http://user:pass@qbittorrent:8090",
```

This is how that should look and you could curl from each of those just to make sure.

`docker exec -it cross-seed curl -i http://prowlarr:9696/2/api?apikey=key`

**Comment by zakkarry** [comment]
You can't use localhost in docker....since you set up a custom docker network, use the container name like @suineg suggested.

**Comment by rtmlp** [comment]
Thanks @suineg. I have updated my post to correctly reflect the context. Do I still have to use the container hostname in the url. Also wondering why it worked earlier with localhost in the url

**Comment by zakkarry** [comment]
> Thanks @suineg. I have updated my post to correctly reflect the context. Do I still have to use the container hostname in the url. Also wondering why it worked earlier with localhost in the url

If you are using a VPN, then you definitely need to use the container names or traffic will be routed to the internet, and you'll never be able to reach prowlarr (assuming you don't have it exposed to the internet) - and if you do....then you'd need to use your internet/external IP, and not anything on your LAN/docker.

**Comment by rtmlp** [comment]
Thanks @zakkarry 

If I have my compose file like below, I won't be able to use the container name because of the network_mode. The only reason I have used `newtork_mode: "service:gluetun` for `cross-seed` is because I don't want `cross-seed` to query trackers with local ip

```Dockerfile
  # gluetun
gluetun:
  image: "qmcgaw/gluetun:latest"
  container_name: gluetun
  hostname: gluetun
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun:/dev/net/tun"
  environment:
    - VPN_TYPE=wireguard
    - VPN_SERVICE_PROVIDER=vpn_provider
    - WIREGUARD_PRIVATE_KEY=key
    - WIREGUARD_PRESHARED_KEY=pass
    - WIREGUARD_ADDRESSES=address
  network_mode: namedbridge
  ports:
    - "8090:8090" # qbittorrent
    - "9696:9696" # prowlarr
    - "2468:2468" # cross-seed
  volumes:
    - "/path/docker/gluetun:/gluetun”

# cross-seed
cross-seed:
  image: crossseed/cross-seed
  container_name: cross-seed
  user: 1029:100 # optional but recommended
  network_mode: "service:gluetun"
  depends_on:
    - gluetun
    - qbittorrent
  volumes:
    - /path/docker/cross-seed/config:/config
    - /path/docker/qbittorrent/qBittorrent/BT_backup:/torrents:ro
    - /path/TD/torrents/completed:/cross-seeds # data folder
  command: daemon
  
  # prowlarr  
  prowlarr:
    container_name: prowlarr
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Los_Angeles
    image: "lscr.io/linuxserver/prowlarr:latest"
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped
    volumes:
      - "/volume1/docker/prowlarr:/config”

qbittorrent:
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8090
    image: lscr.io/linuxserver/qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped
    volumes:
      - "/path/docker/qbittorrent:/config"
      - "/path/td/torrents:/data/torrents”
```

**Comment by zakkarry** [comment]
There is no need to VPN cross-seed, all requests made by cross-seed are done via Prowlarr or directly to your torrent client if using injection.

This will only serve to complicate your setup and prevent communication to the API end points for searches, etc.

Since you VPN Prowlarr already, remove cross-seed's VPN and attempt to use the Docker network IP address and see if that works.

**Comment by rtmlp** [comment]
Thanks for the information @zakkarry I will follow the suggestions
