### ISSUE TITLE
Cross-seed based on data files

### ISSUE THREAD

**Issue by mmgoodnow** [cross-seed/cross-seed#53]
After #52 we'll have an abstraction over searchees. This means that we'll be able to easily create searchees out of entries in your data dirs. 

Plan:
- add a --data-dir command line option that can be used multiple times
- concatenate those with the torrents found in the session dir
- be careful to deduplicate these

**Comment by ajhorvath20** [comment]
This one will be slick. Nice one

**Comment by ajhorvath20** [comment]
I'm keeping an eye on this 👀

**Comment by newadventure079** [comment]
Just an FYI, this is how https://github.com/BC44/Cross-Seed-AutoDL operates

**Comment by mmgoodnow** [comment]
You do have torrent files inside your qbit config, just gotta hunt them down.

**Comment by Byter09** [comment]
I found that folder. Luckily the docker container maps it to the outside so I got access too. Thanks. Hope that wasn't too off topic.

**Comment by mmgoodnow** [comment]
@byter09 No worries! I am gonna mark as off topic though.
