### ISSUE TITLE
FR: Reverse data search

### ISSUE THREAD

**Issue by dsrtusr88** [cross-seed/cross-seed#533]
Would like to be able to do the following:
Drop a `.torrent` file into a watched directory.  When cross-seed sees a new `.torrent` file, it then searches a predefined directory for content that will match the hash from that `.torrent` file.  Useful for trackers with limited to no API support.

**Comment by zakkarry** [comment]
Autotorrent2 does this exact thing already.

**Comment by mmgoodnow** [comment]
are you just going to download all the trackers from
