### ISSUE TITLE
No Search Results using InfoHash (transmission)

### ISSUE THREAD

**Issue by carried-away** [cross-seed/cross-seed#536]
Hello,

I have the post script running after torrent completion for transmission.

I've tested over 10 torrent files that I know are hosted on multiple indexers. They always return

```bash
error: Failed to parse /torrents/69dc62f63accb1111ee4b88575324208968e6e11.torrent
error: could not find a torrent with the criteria { infoHash: '69dc62f63accb1111ee4b88575324208968e6e11' }
```

I'm confused, cross-seed search queries by name and size by default. Why is it highly recommended when using the post processing script with transmission to search by infohash? Not one of the torrents that are on multiple trackers share the same hash. How will it ever find a match?

**Comment by bakerboy448** [comment]
It uses the hash to look up the torrent in the client; the hash is not what is searched

**Comment by carried-away** [comment]
That makes sense. Is there something in transmission's settings where its preventing cross-seed from parsing these torrents? I find that cross-seed search works without issue, I only have a parsing issue with the torrent completion script.

I imagine its using the same logic for both, but I'm out of my depth.

**Comment by zakkarry** [comment]
Make sure that torrent with that exact hash actually is present in your torrent client.

That error leads me to believe it is not.

**Comment by mmgoodnow** [comment]
specifically it looks the torrent up in your torrentDir. So the torrent must be in there

**Comment by mmgoodnow** [comment]
We should change the messaging here-this is a common misconception

**Comment by carried-away** [comment]
Hmm, doing a ls -alh

```bash
-rw------- 1 transmission transmission 20K Oct 31 09:21 .config/transmission-daemon/torrents/1562571db079929e4af258b43282b368924412b7.torrent
```

are R+W permissions enough to parse the torrent file?

**Comment by mmgoodnow** [comment]
Yes

**Comment by mmgoodnow** [comment]
Actually no. The only user that has read permissions is transmission.

**Comment by mmgoodnow** [comment]
You need them to be something like 640 at least

**Comment by carried-away** [comment]
Thank you for pointing me in the right direction, I'll get permissions sorted and see what goes on. Thank you all for your time.

**Comment by carried-away** [comment]
In case anyone is having a transmission specific issues with .torrent file permissions, just run cross-seed as your transmission user.

Unfortunately there's no way out of the box to change how transmission applies chmod 600 permissions to a .torrent file after you add it to the client, 600 gets hardcoded by a posix function.
