### ISSUE TITLE
Can't pull Docker image: Authentication required

### ISSUE THREAD

**Issue by TheColorman** [cross-seed/cross-seed#548]
When pulling the image using `docker pull crossseed/cross-seed` I get the following error:
```powershell
PS C:\Users\thore> docker pull crossseed/cross-seed
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF
```
Similar error on my Linux server.

I realise this might be a docker issue and not a cross-seed issue as I get 401 with "authentication required" when trying to access `https://registry-1.docker.io/v2/`, but I haven't gotten this error with any other docker images.

**Comment by zakkarry** [comment]
Docker Hub issue, has nothing to do with us.

Just have to wait until they fix it.
