### ISSUE TITLE
Not following redirects

### ISSUE THREAD

**Issue by kingofzeal** [cross-seed/cross-seed#549]
I've recently set up cross-seed, and while looking through the verbose logs I'm seeing a recurring issue with one of my trackers:

```2023-11-13 00:30:52 ^[[36mverbose^[[39m: [server] POST /api/announce
2023-11-13 00:30:52 ^[[36mverbose^[[39m: [server] Received announce: Family.Guy.S22E05.1080p.WEB.h264-BAE
2023-11-13 00:30:52 ^[[31merror^[[39m: error downloading torrent at https://www.milkie.cc/api/v1/torrents/AtDQQYfH5dlx/torrent?key=*******: 301 Moved Permanently
2023-11-13 00:30:52 ^[[34mdebug^[[39m: response: <html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

2023-11-13 00:30:52 ^[[36mverbose^[[39m: [decide] Family.Guy.S22E05.720p.WEB.h264-BAE - no match for milkie torrent Family.Guy.S22E05.1080p.WEB.h264-BAE - the torrent file failed to download
```

I'm using autobrr to pass IRC announces into cross-seed, and for other trackers there's no issues. The redirect in this case routes `https://www.milkie.cc` to `https://milkie.cc`. I believe I've found where this URL is coming from to address the root issue, but I also think cross-seed should try to follow redirects if possible.

**Comment by zakkarry** [comment]
I brought this up like 2 weeks ago when it was brought to my attention in the discord....the only issue I thought of with enabling this was how it could potentially be used maliciously....albeit a very marginal chance.

I'll see what I can do to get this fixed soon.

**Comment by kingofzeal** [comment]
Yeah, I can understand the security consideration, but I don't see it at a very high risk - if you're in a position to leverage it, there are so many other things you can do that would be far easier. 

I could also see it being a configuration whitelist, to allow opt-in to the behavior. I'm not sure what you're using under the hood to make these requests, so that could be far more complicated.

And like I said, I _think_ I've addressed the root issue (autobrr had the incorrect root URL), but I still need to verify. 

In any case, I appreciate you looking at it!
