### ISSUE TITLE
Continue search post update, or randomize search.

### ISSUE THREAD

**Issue by SnippetSpace** [cross-seed/cross-seed#554]
For cross-seed running with the search function in a container, every time the container is restarted (for an update for example). The search starts from scratch, in the same order.

In my case I have a tens of thousands of files and thousands of torrents it searches through with a rate of one every few minutes, and thus at every restart of the container it restarts the search from scratch rarely searching the files and torrents low in the alphabet.

2 options to potentially help with this:
1/ store current progress and continue on restart adding on new files/torrents only.
2/ randomize the search so that on restart, there is a higher chance of items later in the queue to be searched, pure randomness is a dirty but good fix in my opinion.

**Comment by SnippetSpace** [comment]
@zakkarry does this work with data searches as well? The wiki never links states this as far as I can see. I'm more concerned with data searches as that is about 35K files for me, torrents only around 4K.

**Comment by zakkarry** [comment]
Yes

**Comment by SnippetSpace** [comment]
Ok thanks, clear!
