### ISSUE TITLE
excludeRecentSearch not working

### ISSUE THREAD

**Issue by ShanaryS** [cross-seed/cross-seed#564]
It keeps searching for the same one with the value set to 26w. I have the limit set to 1 and the interval to 15m and it gets it every 15m. I tried deleting the database and it still happens. Other config options are respected and RSS works well. Some indexers fail each search so maybe it doesn't consider the search complete?

[search] Found 4175 torrents, 4037 suitable to search for matches
[search] Limited to 1 searches

I have seen #284 and tried the SQL commands - select count(*), first_searched, last_searched from searchee group by (first_searched is null), (last_searched is null);

Old DB: 767|1666119580831|1676500618672

Fresh DB: 161||

**Comment by mmgoodnow** [comment]
Why?

**Comment by mmgoodnow** [comment]
It's only re-searching on the indexers that failed.

**Comment by ShanaryS** [comment]
It blocks anything else from being searched. It's stuck grabbing it 24/7.

**Comment by mmgoodnow** [comment]
I would try bumping the limit.

**Comment by ShanaryS** [comment]
It's still searching the same ones.

**Comment by ShanaryS** [comment]
I think the best solution would be to have searchLimit apply per indexer and use exponential backoff for a search per indexer.

**Comment by ShanaryS** [comment]
I found the root cause. One of my indexers were disabled and it was the one causing issues. I must have accidentally disabled it at some point while setting up Prowlarr. I've also verified the same issue with an incorrect torznab link.

I think a check on the URLs would be helpful.
