### ISSUE TITLE
My torrents are injected (qBittorrent) but show missing files error!

### ISSUE THREAD

**Issue by weizsw** [cross-seed/cross-seed#579]
### My scenario:
Some torrents were successfully injected and cross-seeded, while others displayed a missing files error.

### My Cross-Seed Config:
version: ```v5.9.2```
env: ```docker```
matchMode: ```safe```,
action: ```inject```,
duplicateCategories: ```true```,
fuzzySizeThreshold: ```0.02```,

### My QB Config:
autoTMM: ```true```
torrent content layout: ```original```
category path:
    tv-sonarr: ```/Volumes/External/torrents/tv```
external program on torrent finished:
```curl -XPOST http://192.168.50.135:2468/api/webhook?apikey=[REMOVED] --data-urlencode "infoHash=%I"```

### Missing Files torrents:
![image](https://github.com/cross-seed/cross-seed/assets/18436032/be05ece1-28bf-4157-8709-2f0abefba399)
![image](https://github.com/cross-seed/cross-seed/assets/18436032/b55eeb08-c164-45d0-b97d-384cf536516c)
![image](https://github.com/cross-seed/cross-seed/assets/18436032/3d4c2abf-c162-42e2-bed6-64bd0498e97c)

there are a few torrents facing the same condition
![image](https://github.com/cross-seed/cross-seed/assets/18436032/397fce66-5b1d-43a8-9a3d-a22077587a42)
![image](https://github.com/cross-seed/cross-seed/assets/18436032/d0b35667-b5f6-4d13-8989-cd6bffa1094a)
![image](https://github.com/cross-seed/cross-seed/assets/18436032/655c73e8-31ad-49bb-a6e7-565663530ade)

### Cross-Seed logs when injecting these torrents:
```
info: [server] Received search request: { infoHash: '[REMOVED]' }
info: [torznab] Searching 4 indexers for Reacher.S01.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-MZABI
info: Found Reacher.S01.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-MZABI on FileList.io - injected
info: [server] Found 1 torrents for { infoHash: '[REMOVED]' }
```
for those failed torrents, basically the torrent name is a bit diffrent, either with extra characters or `.` and the content folder's name is different as well, I guess this is the reason it shows missing files? 
is this expected?

**Comment by zakkarry** [comment]
No, and frankly i'm not sure how these would be injecting since it should error with filetree is different.

If you can hop on the discord and make a post in #question-and-help and tag me, maybe we can dive a little deeper.
