### ISSUE TITLE
Add Deluge Torrent Client Support

### ISSUE THREAD

**Issue by Jerrk** [cross-seed/cross-seed#58]
Requesting deluge be added as a supported client 😁

**Comment by mmgoodnow** [comment]
PRs always welcome, otherwise, I'll see if I can get to this in a couple months.

**Comment by Torkiliuz** [comment]
Deluge works if you use `action: "save"`, set `torrentDir` to your `/deluge/state`-folder and add a monitored folder in deluge which is the same folder as `outputDir` for cross-seed.

**Comment by UnPossible-Me** [comment]
> add a monitored folder in deluge which is the same folder as `outputDir` for cross-seed.

Hi, 
Could you please elaborate on this a bit? 

Is this akin to using something like the AutoAdd plugin to watch a folder to torrent links?

**Comment by Torkiliuz** [comment]
> Is this akin to using something like the AutoAdd plugin to watch a folder to torrent links?

Correct. First you need to activate the AutoAdd-plugin in Deluge. 
Then you can add a folder in the AutoAdd-plugin as a watch folder; you may set different options as needed, but I recommend choosing "Delete .torrent after adding" as it keeps the folder from getting cluttered. 
I have set auto managed to "No" under the Options-tab for this watch folder, but I doubt it makes a big difference if you choose to keep this as default.

**Comment by UnPossible-Me** [comment]
I see, thanks for the clarification.

**Comment by Jerrk** [comment]
you mean this? 
https://deluge.readthedocs.io/en/latest/reference/api.html

**Comment by controlol** [comment]
I found some documentation for the deluge [JSON/RPC API](https://deluge.readthedocs.io/en/latest/devguide/how-to/curl-jsonrpc.html).
If some information could be supplied to what functions should be implemented in the class. I would be happy to give it a shot. Since Deluge uses a web server for their API calls, I suppose the implementation would look more like QBittorrent.

**Comment by mmgoodnow** [comment]
@controlol yeah! almost all of the deluge specific code will be in one file, but there'll be some configuration/setup stuff you have to thread through several files. 

You'll want to implement the [TorrentClient](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/clients/TorrentClient.ts#L10-L10) interface, which specifies two methods: `inject` and `validateConfig` (returns void but throws a CrossSeedError if config is invalid)

After that, you'll want to add whatever configuration you need, to [FileConfig](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/configuration.ts#L11-L11) and [RuntimeConfig](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/runtimeConfig.ts#L2-L2). If possible, I'd like to keep the configuration to a single string like it is for rTorrent and qBittorrent. 

You'll also need to add [command-line options](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/cmd.ts#L111-L120)

also you'll need to add to [instantiateDownloadClient](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/clients/TorrentClient.ts#L19-L19)

The config templates as well: [regular](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/config.template.cjs), [docker](https://github.com/cross-seed/cross-seed/blob/de47f627cab5e4dd0dffab2f363462c971c96c5c/src/config.template.docker.cjs)

**Comment by Soulplayer** [comment]
Any progress on this :)?

**Comment by controlol** [comment]
tbh, I remember the file structure was quite overwhelming. So unfortunately I have not made any progress on this.

**Comment by mmgoodnow** [comment]
@controlol If you write the Deluge.ts file, I can do the rest. To test, you can hardcode a Deluge instance inside `instantiateDownloadClient` and run `npm run watch` in one terminal, and `node dist/cmd.js search` in another terminal

**Comment by zakkarry** [comment]
Just for those of you still waiting for this, PR is submitted.

https://github.com/cross-seed/cross-seed/pull/499

**Comment by isaacolsen94** [comment]
I loaded the deluge version on my Unraid server to give it a try and I'm getting the following error. Any guidance on resolving it?

`[31merror[39m: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array`

the only path variable I see is the dataDirs variable and I have the following: 
`dataDirs: ["/mnt/user/downloads/complete", "/mnt/user/movies", "/mnt/user/tvshows"],`

It does show as an Array so are we not supposed to input multiple directories? Should I only put on of those?
