### ISSUE TITLE
bug(logging/search): no results found returns "did not search for...."

### ISSUE THREAD

**Issue by zakkarry** [cross-seed/cross-seed#582]
see title.

**Comment by scratchmex** [comment]
was this ever fixed? I don't know why this torrent is not even tried

```
info: [server] Received search request: { name: 'Dark.Matter.2024.S01E05.1080p.WEB.H264-SuccessfulCrab[TGx]' }
info: [server] Received search request: { infoHash: 'ee53b0ab2c721225d62eaa694ffeb32468219392' }
info: [server] Did not search for { name: 'Dark.Matter.2024.S01E05.1080p.WEB.H264-SuccessfulCrab[TGx]' }
info: [server] Did not search for { infoHash: 'ee53b0ab2c721225d62eaa694ffeb32468219392' }
```

**Comment by zakkarry** [comment]
> was this ever fixed? I don't know why this torrent is not even tried
> 
> ```
> info: [server] Received search request: { name: 'Dark.Matter.2024.S01E05.1080p.WEB.H264-SuccessfulCrab[TGx]' }
> info: [server] Received search request: { infoHash: 'ee53b0ab2c721225d62eaa694ffeb32468219392' }
> info: [server] Did not search for { name: 'Dark.Matter.2024.S01E05.1080p.WEB.H264-SuccessfulCrab[TGx]' }
> info: [server] Did not search for { infoHash: 'ee53b0ab2c721225d62eaa694ffeb32468219392' }
> ```

I can almost guarantee that you have includeNonVideos set to false and this torrent contains a text or nfo or something.

You would want to check the verbose logs from this message and it will tell you exactly why it was no searched.

**Comment by scratchmex** [comment]
I edited my comment and found the solution under [this comment](https://github.com/cross-seed/cross-seed/issues/568#issuecomment-1856822671) before realizing your response, thanks

**Comment by zakkarry** [comment]
> I edited my comment and found the solution under [this comment](https://github.com/cross-seed/cross-seed/issues/568#issuecomment-1856822671) before realizing your response, thanks

Glad you sorted things out.
