### ISSUE TITLE
cross-seed container stops if qBittorrent is not available

### ISSUE THREAD

**Issue by AN1MATEK** [cross-seed/cross-seed#583]
Hello, 

This happened to my a few times already. The topic was briefly discussed in the Discord channel and it was suggested to open an issue here.

This happens in unRAID. The torrent container is behind a VPN container.

This is the last extract from the logs before the program closed.
```
Configuration file already exists.
info: cross-seed v5.9.2
info: Validating your configuration...
Configuration file already exists.
info: cross-seed v5.9.2
info: Validating your configuration...
error: qBittorrent login failed: request to http://10.1.3.20:8888/api/v2/auth/login failed, reason: connect ECONNREFUSED 10.1.3.20:8888
```

**Comment by zakkarry** [comment]
I think the approach to take potentially would be temporarily saving torrents to `outputDir` and retrying upon the next injection to login to inject?

**Comment by zakkarry** [comment]
Following up on this, your log seems to say that it failed to login upon launch, but if i recall you stated that it would fail to connect and crash randomly while running, and this was happening upon restart following the crash?

I'm not sure about changing a failure to start when the client fails at launch. I think it could lead to someone with a misconfiguration to assume things are fine, when they are not.

**Comment by zakkarry** [comment]
Revising this, I would recommend you employ the following.

https://www.cross-seed.org/docs/tutorials/unraid#auto-restart

This is our current position until we have a UI that is separate from daemon operation.

This will restart on transient failure as well as at startup, but keep in mind without a delay it will hammer away until it succeeds.
