### ISSUE TITLE
feat(duplicateCategory): ignore dataCategory when using duplicateCategory

### ISSUE THREAD

**Issue by SnippetSpace** [cross-seed/cross-seed#602]
`duplicateCategories: true ` is essential to avoid chaos with sonarr/radarr. When set to true, and using data based matching and search, this logically creates a duplicate for cross-seed-data as well, called cross-seed-data.cross-seed.

I would argue that duplicateCategories can be disabled for data-based search injections. It creates an additional long category for no good reason. It does not affect the ARRs to disable this.

I might have missed some secondary impact I have not considered
This is obviously not important, just QOL

**Comment by zakkarry** [comment]
Basically, what I think is going on is that this is not technically a bug unless my impression is mistaken.

Your initial search is done, after which when a search is subsequently done a torrent search is done on the previously matched torrent which resides in the data category (cross-seed prefers the torrent as a "source" over the data), and duplicateCategories is applied since it is no longer a data match at that point.

**Comment by SnippetSpace** [comment]
Yes not a bug, as stated just a quality of life improvement. I cannot turn of duplicate categories just for cross seed data as far as I know

**Comment by zakkarry** [comment]
No you cannot, however I guess my question is why would you want a non-data matching torrent to end up in the data category at all?

**Comment by SnippetSpace** [comment]
If it is a cross seed of a data matching torrent, it is also a data matching torrent.

**Comment by zakkarry** [comment]
I don't understand what you mean....

After there is a torrent that exists, it is not a data matched torrent anymore. There is now a torrent to search instead, which is why duplicateCategory is used rather than datacategory.

**Comment by SnippetSpace** [comment]
Data matching creates a hard link to a torrent, then creates the torrent and assigns the cross-seed-data category.

search uses that data based torrent to find copies on other trackers and add them. 

Because duplicates are on it creates a new category called cross-seed-data.cross-seed. This new torrent in this new category still uses the same hard link and is data matched, not matched to actual files stored by the torrent client.

the duplication of categories is useful for categories used by Radar or Sonarr to avoid multiple or stuck imports.

since cross-seed data is not used by the Arrs it does not need a duplicate category to protect the Arrs. All that duplicate category does it create another category with a long name.

therefor for that specific data matching category cross-seed-data.cross-seed could/should be disabled and any matches put directly in cross-seed-data, the original category.

**Comment by zakkarry** [comment]
I'm not entirely sure changing this behavior would have no negative effects on anyone who depends on the suffixes to determine things about the nature of their matches or set share limits, etc.

qBitmanage can easily take any torrents in cross-seed-data.cross-seed and categorize them as you wish, though - into cross-seed-data. That seems like an appropriate interim while we discuss and investigate implications.
