### ISSUE TITLE
feat(decide/match): Allow partial size match above ratio to eliminate nearly all false negatives

### ISSUE THREAD

**Issue by ShanaryS** [cross-seed/cross-seed#610]
## Summary
This feature solves the problem where the presence of a .nfo or subtitles prevent a cross-seed from happening. Essentially holding a multi gb torrent hostage due to a couple bytes. I ran this over 100 torrents and got an extra 150 matches ON TOP of the standard data-based risky. Essentially, this feature brings to false negatives to pretty much zero while adding ZERO false positives. It is exactly as safe as risky data-based matching.

For example, if you have a torrent with a single file ```ubuntu.iso``` and there exists a candidate with files ```ubuntu.iso, ubuntu.nfo```, currently the match will fail and no cross-seeding happens. This feature allows the candidate to match with whatever files present as long as it's above the ratio the user specified e.g 0.99. This essentially solves #357 and #160 in a more general way as the type of file isn't the problem, just their size.

## Implementation

Here is a commit with the implementation: https://github.com/cross-seed/cross-seed/commit/c9f95af

In the decide stage, the candidate file tree is compared for file size matches and is successful if the total matched size is above the ratio. If there is only a single file in the candidate, then it must be an exact size match. This is done as a last step when it would have otherwise reported file tree mismatch. I also implemented the reordering in #597 as it was necessary.

In the action stage, if it's a data based search we hardlink the files needed by matching file size. If either candidate or searchee has duplicate file sizes we save instead as we can't match the files correctly, though this should be rare. If it was a .torrent match, we just save immediately as we don't have the path to hardlink, maybe #572 allows it? I have an external script that fuzzy name search all the torrents and hardlinks that way but that may be out of scope for this project.

Now of course, however it gets to the client it will be stuck at 99.9% and the user would need to manually start the torrent to finish downloading the last few bytes. That could be implemented here but it feels wrong to have cross-seed initiate a download. This can be easily automated elsewhere.

This requires the risky match mode and minParitalMatch to be below 1. If the minPartialMatch is at 1, then the feature is disabled and works as normal. If it's below 1 then it will perform the new behavior. Since this matches multiple files, you could set it at 0.99999 to only get complete matches of torrents with multiple files in data based searching, which I believe wasn't done before. We may want to add a lower bound like 0.9 on minPartialMatch to reduce the chance of user error.

**Comment by zakkarry** [comment]
All PR's for non-major bugs should target the v6-unstable branch, just FYI.

No more feature implementations will be done on the master branch, given the large amount of changes made in v6 and the pain in the ass rebasing becomes.

As a note, #572 does permit what you are talking about (torrent-linking) - and potentially could be leveraged here to some extent.

**Comment by ShanaryS** [comment]
For duplicate file sizes, we could check if there exists a single perfect name match. If the names match uniquely along with the file size match, then it should be safe to link.

**Comment by zakkarry** [comment]
Im not sure tbh, thats waiting  for mg to review, im at the gym gimme a few hours and ill let you know what to base off.

**Comment by zakkarry** [comment]
Considering the work-in-progress that linking currently is, and the behavior changes in v6, I think for the time being it might be best to just wait to address this.

After myself and @mmgoodnow have finalized the linking, I think we can look at this a bit more.

**Comment by ShanaryS** [comment]
The duplicate file sizes solution I describe above works, but I currently only do it in the action stage so it's saved if it fails the test. This gives no issues with search but announce has given two false positives so far. I think https://github.com/cross-seed/cross-seed/issues/606#issuecomment-1984805861 should solve it. If not, we could do this check in the decide stage for just announce or even always since this would create very few false negatives.

**Comment by ShanaryS** [comment]
Looking at my stats, it seems that this doubles your cross seeds over data based risky. So if you have 1,000 cross seeds currently, you would get 1,000 more from partially matching for a total of 2,000.

Once this gets implemented, I think the only thing missing is cross seeding a season when you only have the individual episodes. Which would be complicated to implement and probably not worth it.

**Comment by zakkarry** [comment]
> Looking at my stats, it seems that this doubles your cross seeds over data based risky. So if you have 1,000 cross seeds currently, you would get 1,000 more from partially matching for a total of 2,000.
> 
> Once this gets implemented, I think the only thing missing is cross seeding a season when you only have the individual episodes. Which would be complicated to implement and probably not worth it.

I don't understand what you mean....are you saying that because there are nested (files in folders) files...that with data matching and it recursively going folder search first, then file, it would double your searches?

I have plans to eliminate the redundant searching already since linking in v6 will eliminate the need for recursive searching, but just haven't gotten a formal game plan on how to accomplish it most efficiently.

I'll be on Discord if you want to discuss some of these things and their implementations.

**Comment by ShanaryS** [comment]
There are two ways this gives more matches:
1. By effectively ignoring .nfo, .srt and other small files. Previously, if the candidate has a .nfo while the searchee doesn't this would have reported a SIZE_MISMATCH since the .nfo size won't match with anything.
2. By matching searchees with multiple files as risky based matching was limited to single file searchees. So every FILE_TREE_MISMATCH you would get from #597 is now a match.

I haven't looked into how data matching works but I believe it creates a unique searchee for each file and folder? If so then order wouldn't matter.

I can discuss more a discord if this doesn't make sense. But only assessCandidateHelper and performAction were changed for this (including treating MATCH_FILES_PARTIAL as a match elsewhere in the codebase).

**Comment by Audionut** [comment]
I've noticed FILE_TREE_MISMATCH stopping cross-seeding of torrents where the data is an actual match, but the file tree contained within a .torrent files mismatches.

If partial match mode covers these areas where the ordering of the file trees in the .torrent files is mostly correct, this seems like a much cleaner solution than simply killing FILE_TREE_MISMATCH like I did in my local copy https://github.com/Audionut/cross-seed/pull/1

**Comment by ShanaryS** [comment]
> I've noticed FILE_TREE_MISMATCH stopping cross-seeding of torrents where the data is an actual match, but the file tree contained within a .torrent files mismatches.

Partial match already covers this and more. The only FILE_TREE_MISMATCH that partial will report is:
1. Candidate size <= piece length (Usually for torrents less than <1MB like ebooks, recheck in qbit keeps torrents at 0%)
2. There are duplicate file sizes without an exact name match (We won't know what file to link, has a lot of false positives with .rar parts, never seen it miss a legitimate cross seed)

> If partial match mode covers these areas where the ordering of the file trees in the .torrent files is mostly, but not entirely correct, this seems like a much cleaner solution than simply killing FILE_TREE_MISMATCH like I did in my local copy https://github.com/Audionut/cross-seed/pull/1

Neither risky or partial looks at the file tree. The naming of the files don't matter unless it case 2 I mentioned above in with partial.

**Comment by zakkarry** [comment]
@ShanaryS - I'm not trying to negate any of the upside here, merely curious.

In the case of mixed TV packs, for instance, would this potentially miss those due to the release group (let's say the pack group is called "MIXED" or "SCENE" or something) - is there any utility to adding a list of these type of pack groups to some whitelist?

I'm not sure it would be particularly useful, given the nature of packs and cross-seeding, but the thought merely occurred to me and I'm curious on your thoughts on the implications of such a scenario.

**Comment by ShanaryS** [comment]
> In the case of mixed TV packs, for instance, would this potentially miss those due to the release group

Yeah those would cause misses, but I don't think it would be a lot. If only a single episode is different in a 12 episode pack, then you would need fuzzy size to be at least 9%. I think it would only benefit with large 20+ episode seasons. Mixed packs are also mainly old shows or multi seasons. If it's a multi season pack, it also probably already gets check by dataDirs too.

There is no real downside to adding it aside from a few extra snatches, but I wouldn't expect any matches from partial. However it would be a good case for ensemble matching. Where individual episodes and seasons get combined to create a new searchee. I've been thinking about that but it's kinda tricky to implement.

**Comment by zakkarry** [comment]
I have some theories on how to implement it, it's just thoughts atm though. Might be worth a discussion when we decide to venture down that path.
