### ISSUE TITLE
Feature Request: Reset index failures

### ISSUE THREAD

**Issue by backstab5983** [cross-seed/cross-seed#611]
Occasionally, cross-seed can fail to reach an indexer due to any kind of error (let's suppose the indexer went down for a few minutes for the sake of discussion). On Prowlarr I can manually fix it, and ask for a re-test to make it work again. It would be nice to being able to have a similar function in cross-seed (perhaps in config.js) or know how the program behaves in such circumstance. At the moment I'm seeing that even if the indexer goes down for a minute and it comes back up soon after in Prowlarr, it takes a while for cross-seed to start searching on it again, perhaps around 30 minutes but I have no clue how that works or how it's calculated.

In case I wasn't clear:
Searching for 8 indexers...
One fails 
Search keeps going but now searching for 7 indexers..
Prowlarr gives me an error
Error gets fixed in Prowlarr
Cross-seed keeps going for 7 indexers even after the error in Prowlarr has been fixed for a while and the indexer is working

[Discord discussion](https://discord.com/channels/880949701845872672/1216436004194484254/1216436004194484254)

**Comment by SnippetSpace** [comment]
This could help fix this: https://github.com/cross-seed/cross-seed/issues/608
