### ISSUE TITLE
[feature request] Allow stopping search wtih many warnings/errors

### ISSUE THREAD

**Issue by Audionut** [cross-seed/cross-seed#622]
If there's some issue with a tracker during a search that prevents the tracker being reached during the search, unless I'm mistaken (without editing the config) there's currently no way to run any of the 'exclude' options without continuing to miss the torrents from the tracker that was borked on the initial search.

Editing the config file to only include the original borked tracker, would still require a full search run.

Ideally (https://github.com/cross-seed/cross-seed/issues/623) there could probably be some form of logging on failed searches, either because of timeout of tracker, error downloading or what have you, and a way to run a search on just these results at some future date, but failing that, it would be nice if there was an option to stop the current search after 'x' warn/error is received during a search.

Could then catch and fix issues without the need to run excessive searches again.

**Comment by mmgoodnow** [comment]
> unless I'm mistaken (without editing the config) there's currently no way to run any of the 'exclude' options without continuing to miss the torrents from the tracker that was borked on the initial search.

The exclude options will only exclude trackers that searched successfully in the past. Any trackers that failed searches will be included in the next run.

**Comment by Audionut** [comment]
Excellent, thanks.
