### ISSUE TITLE
[feature request] log failed searches/downloads in a manner that allows specific future searching

### ISSUE THREAD

**Issue by Audionut** [cross-seed/cross-seed#623]
As title. Have these failed searches logged in a manner that allows to run a future search on only these results.

**Comment by mmgoodnow** [comment]
@Audionut are you still interested in this after closing 622?

**Comment by Audionut** [comment]
> @Audionut are you still interested in this after closing 622?

I left open as I thought there might have still been a use  case. But it doesn't really make sense to have the extra code and function above what excluderecent already does, so no.
