### ISSUE TITLE
feature request(hardlinking): Automagically hardlink to differing partition/disk/mount

### ISSUE THREAD

**Issue by Audionut** [cross-seed/cross-seed#625]
Hardlinking seems like the most preferred linking solution, and indeed, https://github.com/cross-seed/cross-seed/pull/619 seeks to set hardlinking as the default.

Currently only one `linkDir:` is allowed to be set, resulting in what would appear to be non-optimal outcomes for those who have media files spread across different partition/disk/mount.

The most ideal solution, for us dumb users, would seem to allow multiple entries within `linkDir:`, where the user can set the directories for each partition/disk/mount, and xseed automagically uses the appropriate directory when linking.

**Comment by NooNameR** [comment]
@Audionut just to confirm you want something like:
```javascript
["/datadir1" => "/linkdir1"]
["/datadir2" => "/linkdir2"]
```

this is kind of solve by mergefs, but might make sense for some cases

**Comment by Audionut** [comment]
mergefs would appear to be unix only.

`"/datadir1" => "/linkdir1"` would undoubtedly work, however in cases with many data directories residing on the one partition, it would seem to be excessive config.

A cleaner solution, IMO:
`linkDir: ["a:\\linked", "b:\\linked", "c:\\linked",]` with xseed automagically linking the data match from the relevant `datadir` to the correct `linkDir`.

**Comment by NooNameR** [comment]
> mergefs would appear to be unix only.
> 
> `"/datadir1" => "/linkdir1"` would undoubtedly work, however in cases with many data directories residing on the one partition, it would seem to be excessive config.
> 
> A cleaner solution, IMO: `linkDir: ["a:\\linked", "b:\\linked", "c:\\linked",]` with xseed automagically linking the data match from the relevant `datadir` to the correct `linkDir`.

there are 2 things:
1. linkdir from torrents (I assume you have only single mount there), otherwise it will be hard to do linking
2. linkdir for data. So data should contains its map:
```javascript
["/linkdir1" => "/datadir1/tv", "/linkdir1/movies"]
["/linkdir2" => "/datadir2/tv", "/linkdir2/movies"]
```

**Comment by Audionut** [comment]
> there are 2 things:
> 
>     1. linkdir from torrents (I assume you have only single mount there), otherwise it will be hard to do linking
> 
>     2. linkdir for data. So data should contains its map:

Don't understand 1, as linking only works with data matching.

2 is good, although it would ideally parse the data directories only from the `linkdir:` config, if enabled, and ignore `datadir:`

So instead of adding directories to `datadir:` and `linkdir:`, with linking enabled, the directories would only need to be added to `linkdir:`.

Fuse system makes sense, and if that does indeed work, it would seem the logical solution. I'll have to edumacate myself though, as I don't understand how a single directory in the xseed config _and_ storage pool, automagically creates the link on the correct disk.

**Comment by mmgoodnow** [comment]
Well, it would be the same way that cross seed would do it.

This seems like a pretty niche feature, so unless we see a swarm of demand for it, we probably won't implement it anytime soon . I would look at solutions for running a single file system on multiple disks, or running multiple instances of cross seed.

**Comment by Audionut** [comment]
I was totally missing that point that everything is in the same mount, so of course the hard link would work within the mount, regardless of the underlying drive structure.

**Comment by zakkarry** [comment]
> > there are 2 things:
> > ```
> > 1. linkdir from torrents (I assume you have only single mount there), otherwise it will be hard to do linking
> > 
> > 2. linkdir for data. So data should contains its map:
> > ```
> 
> Don't understand 1, as linking only works with data matching.

This will change with v6, as torrent-based linking has been implemented if appropriately configured

> 2 is good, although it would ideally parse the data directories only from the `linkdir:` config, if enabled, and ignore `datadir:`
> 
> So instead of adding directories to `datadir:` and `linkdir:`, with linking enabled, the directories would only need to be added to `linkdir:`.
> 
> Fuse system makes sense, and if that does indeed work, it would seem the logical solution. I'll have to edumacate myself though, as I don't understand how a single directory in the xseed config _and_ storage pool, automagically creates the link on the correct disk.

This is how unraid operates, and I believe even mergerfs works in this manner. This is the general consensus on how to accomplish this currently. It requires some reading and understanding of the implementation, but isn't overly complex.

I don't think someone's unwillingness and laziness to get their system configured in a way that accomplishes their desires is necessarily something we should just "solve" for them. It's not a small task, but it's not like a huge hurdle for the user. Spend a few hours and you can have it up rather easily without us "doing it for them" - just my thoughts though.

I don't mean to sound like I'm attacking, but there are solutions to this issue, and the implementation isn't something we necessarily have to prioritize to accommodate people who don't want to bother with getting their system setup in a way to facilitate the optimal setup.
