### ISSUE TITLE
bug(torrent/redirect): error?.cause can be undefined

### ISSUE THREAD

**Issue by ShanaryS** [cross-seed/cross-seed#628]
Noticed this message in my logs for a while on the main branch:
```Cannot read properties of undefined (reading 'message')```

?.message seems to solve it. Not sure if it's just me.
https://github.com/cross-seed/cross-seed/blob/08099538f28244c9dd57ecd542aff6202c7f9dfc/src/torrent.ts#L43

**Comment by mmgoodnow** [comment]
this is fixed in v6
