### ISSUE TITLE
Question: infoHash Matching

### ISSUE THREAD

**Issue by xags** [cross-seed/cross-seed#630]
When performing a POST to the /api/webhook endpoint with a valid infohash I am noticing that when a valid result is returned and auto-imported into my client (non-RPC/not injecting) I'm not seeing a symlink get created to reference the original files location.

I have both the dataDirs and linkDir defined with linkType as symlink.

When I perform a path search, it works fine and creates the symlink. Path based matching is less desirable and returns fewer eligible results.

I suppose this is because by just sending a call with an infoHash, cross-seed has no idea where the original path/file are located so it can't create a link. 

Is there a way to use/call with the infoHash but reference the file destination so that the symlink can be created?

**Comment by zakkarry** [comment]
in v5 torrent matches do not link files, they directly reference them.

this is a feature present in v6, but that is not released yet.

**Comment by xags** [comment]
> in v5 torrent matches do not link files, they directly reference them.
> 
> this is a feature present in v6, but that is not released yet.

So the only way to make this work currently is searching with the path instead correct?
