### ISSUE TITLE
feat(regex): Anime episode matching

### ISSUE THREAD

**Issue by ShanaryS** [cross-seed/cross-seed#631]
Some anime release groups follow the standard episode formats and match correctly. However a very large portion does not. They usually follow "[group] title - episode" with variations on that. The goal here to search the non standard anime using "title episode". This gives the best matching and is how sonarr does it (They do a bunch of simultaneous searches using all title variations and search types, often 5+ per indexer). However since we are looking for cross seeds an not just searching, we can assume the naming is the same with one caveat.

Often release will include the English and Japanese title as "title (altTitle)" with no consistency with which goes where. Whatever in the parenthesis is matched as altTitle which could also be used for the search query. Since we don't want to do multiple searches, we could randomly chose between the two if altTitle is present. That should allow both to be searched eventually once excludeRecentSearch rolls over. Some trackers might rename the title to be only in English with their standard so we should cover both.

These searches are also helped by removing all [] brackets as well as Japanese style brackets. The regex accounts for these but it would be helpful even in non anime releases. https://regex101.com/r/m8AO1m/3

I tried to make this match only the anime style but in order to catch as many conventions as possible it can match movies and ep/season regex. So this must be used after those fail.

I tested this across 2000+ releases on nyaa with some old releases and isolated all the unique conventions. It should parse pretty much every thing that EP_REGEX fails to get. In the test string I have some marked as failures as they won't match reformatted titles but they should be rare. I also couldn't find a reasonable way to match altTitle at the start or end which was less common.

https://regex101.com/r/F9uPn0/4

**Comment by bakerboy448** [comment]
Sonarr does not search episode titles except for specials

**Comment by zakkarry** [comment]
Not interested in leveraging outside services as a requirement for standard features, if the torrent names don't come up from a search it kinda is what it is in my view.

This is why I didn't bother with anime and still don't think it's a venture worth pursuing to _MUCH_ extent.

If @ShanaryS can provide something contained that increases cross-seeds without detrimenting anything else, he's free to pursue it. 

Just be advised that we weren't unaware of the lack of functionality as it relates to anime, we didn't want to deal with the headaches.
