### ISSUE TITLE
Linking fails when actual directory structure does not match torrent's file tree

### ISSUE THREAD

**Issue by Audionut** [cross-seed/cross-seed#680]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

cross-seed is trying to match against a torrent that has had it's file structure modified to match an existing, already seeding torrent.

### Reproducing the bug

Download torrent A (the source): https://pastebin.com/CwxwJ9UU - seed it.

Open torrent B (the searchee) in client: https://pastebin.com/S5N1S1Ug - Modify the file structure of the torrent in client to match the existing seed (torrent A).

>  infoHash: '3d72404e9acf96117d1dba92666d0c14d9b46b41',
>   name: 'Never.Steal.Anything.Small.1959.1080p.Blu-ray.AVC.DTS-HD.MA.2.0',
>   length: 29978065295

Thus the actual `on disk structure` from torrent B ceases to match the `info hash structure`, since it's been modified in client to match:

> infoHash: '69bae85b8fc532c0e07784ca8c39b1d533ea472d',
>   name: 'Never Steal Anything Small',
>   length: 29978065295

From the source (torrent A).

Cross seed at some later date, decides to use torrent B to perform the searchee, resulting in a match with torrent C (the candidate): https://pastebin.com/xb80x8pE
Whose `info hash structure` matches torrent B:

>   infoHash: '077fc5a1154c4049af86ccbfc5f0a5c740d1b76d',
>   name: 'Never.Steal.Anything.Small.1959.1080p.Blu-ray.AVC.DTS-HD.MA.2.0',
>   length: 29978065295

But crucially, the actual `on disk structure` is not a match, despite the info hash structures matching, resulting in less than optimal.

```
2024-05-10 22:38:24 [36mverbose[39m: [qbittorrent] Making request (3) to /torrents/info with body "hashes=3d72404e9acf96117d1dba92666d0c14d9b46b41"
2024-05-10 22:38:24 [31merror[39m: Linking failed, Z:\Movies\Never.Steal.Anything.Small.1959.1080p.Blu-ray.AVC.DTS-HD.MA.2.0 not found. Make sure Docker volume mounts are set up properly.
2024-05-10 22:38:24 [33mwarn[39m: Falling back to non-linking.
2024-05-10 22:38:24 [36mverbose[39m: [qbittorrent] Making request (3) to /torrents/info with body "hashes=077fc5a1154c4049af86ccbfc5f0a5c740d1b76d"
2024-05-10 22:38:24 [36mverbose[39m: [qbittorrent] Failed to retrieve torrent info using infohash_v1 077fc5a1154c4049af86ccbfc5f0a5c740d1b76d, checking all hashes
2024-05-10 22:38:24 [36mverbose[39m: [qbittorrent] Making request (3) to /torrents/info with body ""
2024-05-10 22:38:26 [36mverbose[39m: [qbittorrent] Making request (3) to /torrents/info with body "hashes=3d72404e9acf96117d1dba92666d0c14d9b46b41"
2024-05-10 22:38:26 [36mverbose[39m: [qbittorrent] Making request (3) to /torrents/add with body {}
2024-05-10 22:38:27 [36mverbose[39m: [qbittorrent] Making request (3) to /torrents/info with body "hashes=077fc5a1154c4049af86ccbfc5f0a5c740d1b76d"
2024-05-10 22:38:27 [32minfo[39m: Found [32m[1mNever.Steal.Anything.Small.1959.1080p.Blu-ray.AVC.DTS-HD.MA.2.0[22m[39m on [1mPassThePopcorn[22m by MATCH - injected
```

The candidate is injected into the client with the clients default save path.

### What should be happening?

Get the `content_path` from the client, for example https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#user-content-get-torrent-list

Check that the content path matches the torrent file tree structure from the info_hash of the candidate. Link appropriately.

Of note, the error message, `Make sure Docker volume mounts are set up properly`, should be changed, since docker is not applicable at all in my setup.

### Your setup

```markdown
Irrelevant
```

### config.js (REDACT SENSITIVE INFORMATION)

Irrelevant

### verbose logs

Added above

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by Audionut** [comment]
In discord, the requests of me were seemingly needed within seconds, and being lost within the elitist attitude of people more interested in attacking setup, and playing linux gods, than problem solving.

> This shouldn't be happening

Is a response I have been given previously, and yet my persistence demonstrated issues with the source code, resulting in necessary code refinements. I have also focused on contributing towards this project, rather than being a user who only wants, without giving.

But this attitude I'm getting, including just now when you feel it necessary to blabber on about past events. I have better things to do. At least now, you can confirm the issue when other users present the same. Thanks for putting my mind at ease in how I need to deal with this mis-matching structure issue in the future.

**Comment by zakkarry** [comment]
Past events are relevant, as they are a preface and context to how you are handling this, even now. Rather than continue a conversation where we requested information, regardless of who, because its "irrelevant" to you. You never once provided, or even mentioned, crucial information that would have given everyone the answer almost immediately until making an issue on github.

You were there, you even took things to another channel, but even then you left before answering the multiple questions and resolving this, and then came to the github and made an issue while still deeming certain parts of the bug report "irrelevant".

I don't know if you're being difficult on purpose, but you're not making things as easy as they could/should be.

**Comment by Audionut** [comment]
Talk about beating a dead horse, seriously. 

The current functionality means that cross seed erroneously processes a torrent (b) as a MATCH, when it is not.
The current functionality means that cross seed skips correct matches (a), due to it's erroneous handling of b torrents.

**Comment by zakkarry** [comment]
The indexing is done based on the .torrent files, not the state of the modified torrent in the client.

The solution is to stop modifying the torrents in the client. We do not index the structure from the client, and we never have.

**Comment by Audionut** [comment]
Absolutely, not modifying torrents in client is the correct solution, but it doesn't undo 20 years of previous mismanagement. For fear of this point becoming an unnecessary extended argument, yes, that mismanagement can be solved at this keyboard.

> We do not index the structure from the client, and we never have.

Leading to erroneous results. Whether you wish to extend the validation of torrent indexing, and thus torrent injection, based on this condition, is totally up to you of course.

**Comment by mmgoodnow** [comment]
Thanks for this report, I understand it now. I wouldn't really call this a bug as cross seed hasn't historically supported renamed torrents. That said, I did think we were aiming to support this kind of thing in v6 (it's similar to supporting Subfolder content layout).

If possible, I'd recommend removing the renamed torrents and rerunning cross seed to reseed. Alternatively you might be able to use autotorrent since you already have the torrent files, but I'm not sure if autotorrent can handle renamed files either.

For what it's worth, I think you will have a more pleasant user experience on all your apps if you are able to move to a more standard setup. Volunteer based projects like this are constrained primarily by contributors' time, and supporting highly custom setups is generally not something we can afford to spend our time on.
