### ISSUE TITLE
Denylist or Allowlist Categories

### ISSUE THREAD

**Issue by nod44** [cross-seed/cross-seed#688]
### Does an existing issue/feature request already exist?

- [X] I've searched far and wide!

### Does your feature request solve a problem you're facing?

Large seedboxes have categories of files (arr apps, custom categories, etc.).  As a user having a large seedbox, I have many categories in my qbittorrent instance which have very low cross-seed potential, and I would like to exclude them.  For instance, this is especially true with adult content / whisparr -- but there are situations where I might want to sync radarr and not sonarr, for example.

### What would you like for cross-seed to do?

I would like the product to lookup the category of the torrent file actively in qbittorrent prior to executing a search.  If that category is in the deny list (or inversely not in the allow list, if that is enabled), permanently skip that torrent.

### What are you currently doing, if anything, to solve or work around the issue?

Nothing -- useless searches are being executed.

### Additional comments

I am unsure if this information is already available via the client integrations, but it seems plausible that it is, based on the handling of duplicate categories.

**Comment by zakkarry** [comment]
https://github.com/cross-seed/cross-seed/issues/395

Seems you didn't search that far or wide.

Duplicate issue.
