### ISSUE TITLE
bug when matching cases-sensitive repack/proper and periods in group

### ISSUE THREAD

**Issue by NLZ** [cross-seed/cross-seed#700]
### Does an existing issue/feature request already exist?

- [X] I've searched far and wide!

### Does your feature request solve a problem you're facing?

The group E.N.D is still not detected properly in v6 safe mode.
v6: `[decide] Akira 1988 Repack 1080p Blu-ray Remux AVC Atmos-E.N.D.mkv - no match for Aither torrent Akira.1988.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.HYBRID.REMUX-FraMeSToR.mkv - it has a different release group: undefined -> FraMeSToR`
But at it found matches even like this, I guess because it matched undefined to undefined, compared to v5 where it didn't work.
v5: `[decide] Akira 1988 Repack 1080p Blu-ray Remux AVC Atmos-E.N.D.mkv - no match for Aither torrent Akira 1988 Repack 1080p Blu-ray Remux AVC Atmos-E.N.D.mkv - it has a different release group`
Not sure why it fails to detect it, maybe it doesn't like the dots.

It also seems to have trouble with `Repack`, guess because it's not all caps
`[decide] Akira 1988 Repack 1080p Blu-ray Remux AVC Atmos-E.N.D.mkv - no match for MoreThanTV torrent Akira.1988.REPACK.Dual.Audio.1080p.BluRay.Remux.FLAC.2.0.H.264-E.N.D - one is a different subsequent release: INITIAL -> REPACK`
(I don't get MTV put different audio codec in the release title, the filename is the same)

### What would you like for cross-seed to do?

It seems like a cosmetic thing at this point as the matching undefined to undefined works in v6.
Same with the unrecognized Repack to Repack, except when uploaders are being creative.

### What are you currently doing, if anything, to solve or work around the issue?

Manual matching

### Additional comments

.

**Comment by zakkarry** [comment]
the thing about the matching groups is _MORE OR LESS_ irrelevant outside of the logging message - the repack/proper stuff is a bug - I've opened a PR to address this

in regards to the group, unless the group is renamed in the candidate, it will never be undefined in one and something in the other that should be a match and undefined to undefined is a match so I'm not sure that's something that really needs to be addressed functionally.

as long as we are equally applying them across the local and remote, the matching is fine.

i get that its not logging it correctly but it doesn't affect matching as long as the group is consistent across the two releases
which it should almost always be outside of the uploader tagging, which we already account for.
