### ISSUE TITLE
Fix logging for Transmission errors

### ISSUE THREAD

**Issue by rgossiaux** [cross-seed/cross-seed#702]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

https://github.com/cross-seed/cross-seed/blob/7ba8184ceb8e7cbd5f99ab1f8ee5e908597434e6/src/clients/Transmission.ts#L95

This is only checking for a `TypeError`, but if you receive an HTML response and try to parse it like this you're going to get a `SyntaxError`, which means this branch isn't trigger and you're not dumping the response body into the logs.

Trying to set up cross-seed and I'm getting some kind of error from Transmission, and this logging bug means I can't actually see what's going wrong in the logs

### Reproducing the bug

You can repro this easily by changing your transmission URL to http://www.google.com

### What should be happening?

code should check for `SyntaxError`

### Your setup

```markdown
n/a
```

### config.js (REDACT SENSITIVE INFORMATION)

n/a

### verbose logs

2024-06-02 01:58:47 error: [transmission] Transmission responded with an error
2024-06-02 01:58:47 debug: Unexpected token < in JSON at position 0
2024-06-02 01:58:47 error: Failed to reach Transmission at http://[REDACTED]:[REDACTED]@[REDACTED]:9091/transmission/rpc

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
Can you get on Discord and get my attention so I can try and help you troubleshoot this a bit more to find out how we can distinguish these errors that don't return ErrorType that you're experiencing?
