### ISSUE TITLE
Release group parsing with KG and Jackett not working well

### ISSUE THREAD

**Issue by rgossiaux** [cross-seed/cross-seed#706]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

The release group matching is preventing this KG torrent from matching with itself, let alone the cross uploaded version on PTP.

```
2024-06-06 04:04:15 verbose: [decide] Nizvodno.od.sunca.AKA.Downstream.from.the.Sun.1969.720p.HDTV.mkv - no match for Karagarga torrent Nizvodno od sunca AKA Downstream from the Sun 1969 Yugoslavia [Nizvodno.od.sunca.AKA.Downstream.from.the.Sun.1969.720p.HDTV.mkv] - it has a different release group
2024-06-06 04:04:15 verbose: [decide] Nizvodno.od.sunca.AKA.Downstream.from.the.Sun.1969.720p.HDTV.mkv - no match for PassThePopcorn torrent Nizvodno.od.sunca.AKA.Downstream.from.the.Sun.1969.720p.HDTV - it has a different release group
```

### What should be happening?

These should be matches.

### Your setup

```markdown
- OS: Debian 12
- Prowlarr/Jackett: Jackett Version v0.22.66
- Docker: yes (`image: ghcr.io/cross-seed/cross-seed`)
- Misc:
```

### config.js (REDACT SENSITIVE INFORMATION)

```
module.exports = {
    delay: 10,
    torznab: [
        REDACTED
    ],
    dataDirs: ["/data"],
    matchMode: "safe",
    dataCategory: undefined,
    linkDir: "/links",
    linkType: "symlink",
    skipRecheck: false,
    maxDataDepth: 2,
    torrentDir: "/torrents",
    outputDir: "/cross-seeds",
    includeEpisodes: false,
    includeSingleEpisodes: true,
    includeNonVideos: true,
    fuzzySizeThreshold: 0.02,
    excludeOlder: undefined,
    excludeRecentSearch: undefined,
    action: "inject",
    rtorrentRpcUrl: undefined,
    qbittorrentUrl: undefined,
    transmissionRpcUrl: "REDACTED",
    delugeRpcUrl: undefined,
    duplicateCategories: false,
    notificationWebhookUrl: undefined,
    port: 2468,
    host: undefined,
    apiAuth: true,
    rssCadence: undefined,
    searchCadence: undefined,
    snatchTimeout: undefined,
    searchTimeout: undefined,
    searchLimit: undefined,
};
```

### verbose logs

See above

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
Both of these cases should be fixed in the pre-release versions of 6.

**Comment by zakkarry** [comment]
#592
