### ISSUE TITLE
Default Save Path in qBittorrent is not being correctly defined

### ISSUE THREAD

**Issue by gugatinho** [cross-seed/cross-seed#718]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

Categories created with default blank save path are used by cross-seed only as save path not adding category name

When creating a category and not defining a save path, categories.json will have blank as save path. But qBittorrent consider default save path/category name as save path

Consider save path as /downloads and these category

{
    "sample": {
        "save_path": ""
    },
…
}

qBittorrent uses /downloads/sample, cross-seed injects as /downloads only when matches

It's happening from 6.0.0-3 to 6.0.0-10

Versions 5.x and 6.0.0-0 work fine

### Reproducing the bug

In qBittorrent, create a new category with save path as blank

Put a torrent that will be match in that new category

Force a search

New torrent will be missing files because path will be /downloads and not /downlows/new

### What should be happening?

Path, if it's blank on categories.json, should be /default_path/category_name

Like /downloads/sample

### Your setup

```markdown
not relevant

- OS: Debian GNU/Linux 11 (bullseye)
- Jackett: 0.22.106
- Docker: 26.1.4
- qBitTorrent 4.6.3-4.6.5
```

### config.js (REDACT SENSITIVE INFORMATION)

not really relevant

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
module.exports = {
    torznab: ["REDACTED"],
    host: undefined,
    port: 2468,
    notificationWebhookUrl: undefined,
    rtorrentRpcUrl: undefined,
    qbittorrentUrl: "http://REDACTED",
    transmissionRpcUrl: undefined,
    delugeRpcUrl: undefined,
    delay: 30,
    dataDirs: [],
    matchMode: "safe",
    dataCategory: undefined,
    linkDir: undefined,
    linkType: "symlink",
    legacyLinking: false,
    skipRecheck: true,
    maxDataDepth: 2,
    torrentDir: "/torrents",
    outputDir: "/cross-seeds",
    includeEpisodes: true,
    includeSingleEpisodes: false,
    includeNonVideos: true,
    fuzzySizeThreshold: 0.02,
    excludeOlder: "4 weeks",
    excludeRecentSearch: "1 week",
    action: "inject",
    duplicateCategories: false,
    snatchTimeout: undefined,
    searchTimeout: undefined,
    searchLimit: undefined,
//# sourceMappingURL=config.template.cjs.map

### verbose logs

Missing file message: https://imgur.com/a/Dwng4x4

Configuration file already exists.
2024-06-12 04:51:30 info: cross-seed v6.0.0-10
2024-06-12 04:51:30 info: Validating your configuration...
2024-06-12 04:51:31 info: Your configuration is valid!
2024-06-12 04:51:31 info: [server] Server is running on port 2468, ^C to stop.
2024-06-12 04:51:56 info: [server] Received search request: { infoHash: 'REDACTED' }
2024-06-12 04:52:25 info: Searching for REDACTED [REDACTED] | MediaType: REDACTED | IDs: NONE
2024-06-12 04:52:41 info: Found  [REDACTED] on REDACTED by MATCH from torrentDir (REDACTED [REDACTED]) - injected
2024-06-12 04:52:41 info: [server] Found 1 torrents for { infoHash: 'REDACTED' }

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
Not a bug, and I do not recall any conversation in the Discord server you acknowledged you came to in attempt to solve this.

Support issue, not a bug.
