### ISSUE TITLE
v6 - support season packs in data based matching by using Sonarr's grab history

### ISSUE THREAD

**Issue by Schaka** [cross-seed/cross-seed#726]
### Does an existing issue/feature request already exist?

- [X] I've searched far and wide!

### Does your feature request solve a problem you're facing?

Currently, data based matching doesn't find season packs if the season folder has been renamed.
It's "pretty normal" for Sonarr to just create a folder called "Season 2". 

While it's probably possible restore a potential folder name from episode names inside and then using data based matching the same way it works on movie folders or files, I think now that Sonarr's implementation in v6 is pretty solid, this would be the way to do it.

### What would you like for cross-seed to do?

Sonarr's grab history contains the original torrent, usenet grab or manual import (and where from). It contains info about grabs, renames, etc. 

It should be fairly "easy" to use this info to do something like:
- (temporary) hardlinks for episodes in an originally named folder
- check if torrent (hash?) matches on the files and if yes inject to client
- delete folder (with hardlinks) if no matches were found at all

Obviously you do know better and I'm not too familiar with cross-seed's code to tell you exactly what to do. But I think this would be somewhat of a workaround for the problem with data based matching.

Granted, this would be a new "source" for your data to begin with. You're looking at the *arrs to find the data they (and their folders) contain, rather than scanning the file system. If no history is available, I don't think there's anything to do.

### What are you currently doing, if anything, to solve or work around the issue?

I sit it out and accept that some older files on my drives may never be seeded back because I can't recall where I got them.

### Additional comments

https://sonarr.tv/docs/api/#/History

I do something similar to check if files are still seeding [in Janitorr](https://github.com/Schaka/janitorr/blob/develop/src/main/kotlin/com/github/schaka/janitorr/servarr/sonarr/SonarrRestService.kt).

**Comment by zakkarry** [comment]
So in searching "far and wide" - did you miss the entire open PR that solves what I think you are asking for?

#695

**Comment by Schaka** [comment]
I looked at open issues, not at open PRs.

Having a look at the PR, I see that it re-enables `Season 0X` folders on your file system. 
Assuming that fuzzy matching will work here, it **may** solve what I asked.

I'm not sure the percentage of matches will be nearly as high as looking at Sonarr's history for original names.

Working from Sonarr as a starting point, or from a folder (matched to Sonarr show via path), you could:

- Make an API call to get available seasons
- Look for rename events in that season's history upon import
- recreate (temporarily and match against that

I don't see that in the PR and this wouldn't require any web hooks to be implemented by Sonarr first.
It's possible that this is a dumb solution - again, I don't know cross-seed in an out like you likely do.

Ignoring the not-so-great example, this is Sonarr's visual representation of their per-season history API:
![image](https://github.com/cross-seed/cross-seed/assets/2223171/34da6150-cba0-42b4-a643-12c524b7bdcc)

**Comment by zakkarry** [comment]
Assuming you are using a halfway reasonable naming scheme for the renamed media, we recommend [this](https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/) from the trash-guides - you shouldn't have any issues.

If you do the above, there is no need to reconstruct the folder structure as you are describing for searching or querying any additional information from Sonarr.

**Comment by Schaka** [comment]
I do use the TRaSH Guides naming scheme. The instance of Sonarr I had available remotely to give you that example has renaming turned off, but I do use it locally, which is what promoted this issue.

I'll keep an eye out on the PR being merged and will report back whether it catches season folders with data based matching after the merge.

**Comment by zakkarry** [comment]
I mean...that's exactly what it's designed (and tested) to do so... ;P

**Comment by Schaka** [comment]
I figured I'd give it a shot and used the `:season-folder-webhook` image this morning.

Would season folders have to be registered via Sonarr webhooks for this to work at all? Or do I have to delete my cross-seed database so it doesn't skip season folders?

Because out of the box on my existing config, it unfortunately ignores season folders still.

**Comment by zakkarry** [comment]
I'd advise you to get on the Discord and message me - I've had a couple of people test this branch and they have found matches.

https://cross-seed.org has a icon in the top right or if you want to give em your IRC details I can message you there alternatively.

**Comment by Schaka** [comment]
Tested that branch thoroughly enough. Works for me.
