### ISSUE TITLE
Vanilla install of V6 on vanilla windows fails to pinpoint correct directory

### ISSUE THREAD

**Issue by Audionut** [cross-seed/cross-seed#766]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

cross-seed is attempting to access an incorrect directory.

### Reproducing the bug

Vanilla everything.
Install per-requisites.
Install cross-seed V6
run cross-seed

### What should be happening?

Correct functionality as V5

### Your setup

```markdown
- OS: Windows 11 x64
- Prowlarr/Jackett: 
- Docker: 
- Misc:
```

### config.js (REDACT SENSITIVE INFORMATION)

Not applicable

### verbose logs

```
D:\cross-seed>npm install -g cross-seed@next

changed 105 packages in 5s

18 packages are looking for funding
  run `npm fund` for details

D:\cross-seed>cross-seed
file:///C:/Users/Audionut/AppData/Roaming/npm/node_modules/cross-seed/dist/configuration.js:29
        throw new CrossSeedError(`cross-seed does not have R/W permissions on your config directory.${dockerMessage}`);
              ^

[CrossSeedError: cross-seed does not have R/W permissions on your config directory.]

Node.js v20.16.0

D:\cross-seed>npm install -g cross-seed

added 6 packages, removed 4 packages, and changed 101 packages in 4s

18 packages are looking for funding
  run `npm fund` for details

D:\cross-seed>cross-seed gen-config
Configuration file created at C:\Users\Audionut\AppData\Local\cross-seed\config.js

D:\cross-seed>npm install -g cross-seed@next

added 4 packages, removed 6 packages, and changed 101 packages in 1s

18 packages are looking for funding
  run `npm fund` for details

D:\cross-seed>cross-seed

C:\Users\Audionut\AppData\Local\cross-seed\config.js:32
                        "http://127.0.0.1:9117/api/v2.0/indexers/xxxxxxx],
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Your config file is improperly formatted. The location of the error is above, but you may have to look backwards to see the root cause.
Make sure that
  - strings (words, URLs, etc) are wrapped in "quotation marks"
  - any arrays (lists of things, even one thing) are wrapped in [square brackets]
  - every entry has a comma after it, including inside arrays
  
D:\cross-seed>cross-seed daemon
2024-07-31 22:50:35 info: cross-seed v6.0.0-27
2024-07-31 22:50:35 info: Validating your configuration...
```

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by bakerboy448** [comment]
And can you link to your discord support thread where this permissions issue was confirmed to be a bug?

**Comment by zakkarry** [comment]
The way we "pinpoint" the correct path for the configuration directory has not changed between v5 and v6, only that we also check permissions on the filesystem in 6.

Your filesystem is reporting that it does not have the proper permissions for the user you're running cross-seed as to read and write to that path.

v5 is not "functioning correctly" - it just is not validating the permissions at all. v6 does.

We use fs.accessSync to validate permissions. Seems very much like a support issue you did not seek support on and given that you are not the first person to use windows with cross-seed v6, unless you can provide context on how to produce this outcome consistently with proper permissions set, I'm not sure where we're supposed to go other than advising you to fix your permissions on the config path.

"Install v6 and run it" does not produce this for me on Windows.

**Comment by zakkarry** [comment]
I'm following up here @Audionut - is there further instructions you can give to produce this outcome? Was this resolved?

**Comment by Audionut** [comment]
Have you tried a vanilla (no previous install (of any version)) install of V6.

'Everyone' was appointed as the owner of the folder (/npm/), with 'Everyone' having all of the permissions required to burn the folder to smithereens. And of course, the terminal had Admin privileges.

As the verbose log demonstrates, the resolution was to install V5 first, use that version to generate the config file (somehow magically bypassing supposed permissions issues) and then install V6.

Thinking back, what I didn't do was touch any permissions related to 'Users\Audionut\AppData\Local', but that still doesn't make sense, because the logged in account has the required permissions. Furthermore, if the functionality has not changed between versions, and it is indeed a real permissions issue, then V5 should silently fail, as apposed to actually work.

**Comment by zakkarry** [comment]
I was able to replicate your scenario by entirely removing the folder rather than just its contents, which was a oversight I had previously made with the del command I used. 

I'll investigate what is going on here a bit more.

After the creation with v5, you were then able to use v6 normally?

**Comment by zakkarry** [comment]
I think I see why this is occurring.

**Comment by zakkarry** [comment]
If you had created the directory, it would have done the rest just fine, FYI.

This should be fixed by the PR I've linked here. 

Thank you for taking the time to bring this up.

**Comment by Audionut** [comment]
The level of aggression displayed by children here is really unnecessary. It's really remarkable how a simple act of leaving a discord server can create so much animosity. I'm not entirely sure what such behavior is supposed to be proving, but it does certainly reinforce existing community expectations.

I persisted in posting this issue, persisted past the abuse, and in ensuring understanding of the issue on behalf of all of those future users who may not know any better, and who shouldn't be treated the way this community treats them. Or maybe it's just my username that causes a short circuit in some of the brains around here.
