### ISSUE TITLE
Data support in rss/announce

### ISSUE THREAD

**Issue by winterberryteastories** [cross-seed/cross-seed#795]
## Use case

 racing new torrent releases with usenet (or other means) downloads.

In order to do so `/announce` (sent e.g. by autobrr) or rss would need to check the `dataDirs` for any matches, but currently only checks for matching .torrent files.

While interesting for some (ppl migrating from usenet to slower-to-release trackers) it's probably still an edge case for most.

## Notes 
I was thinking instead of pressuring I/O with looking for files on every `/announce` there are a few options:

a) it could scan `dataDirs` periodically and keep a cache and when an `/webhook` (or a new API call) comes in with `path` add that path to the cache. Then on `/announce` just check those in a similar way it is done for the search command.

b) check with the help of the sonarr/radarr api if that episode/season pack/movie exists and only consider the related file for the search. (probably undesired because of external dependencies, then maybe a simple plugin system would be nice to easily plugin such custom functionality myself)

**Comment by ShanaryS** [comment]
#857
