### ISSUE TITLE
Modify saved torrent retry injection logic to give up

### ISSUE THREAD

**Issue by Audionut** [cross-seed/cross-seed#798]
### Does an existing issue/feature request already exist?

- [X] I've searched far and wide!

### Does your feature request solve a problem you're facing?

Not a problem per se, but further automation of the excellent feature would be nice.

### What would you like for cross-seed to do?

In this specific instance:
```
2024-09-24 17:30:41 warn: [inject] (1/1) Unable to inject xxxxxx[movie][xxxxxxc...].torrent - ALREADY_EXISTS (incomplete)
2024-09-24 17:30:41 info: [inject] Injected 0/1 torrents, 1 existed in client (1 were incomplete)
```
It feels like the logical solution is to just stop.

But what originally piped my interest was when I run cross-seed for the first time with fresh data, without common knowledge of this feature.

- failed to inject, saving
- retry logic successfully injects
- user deletes torrent from client
- retry logic successfully injects
- rinse and repeat.

A bit of a head scratch to understand why these torrents being deleted from the client kept getting injected lol. I don't have the log handy, but presumably these were marked as successfully injected, in which case the logical solution would also seem to be, stop trying to inject ever hour.

### What are you currently doing, if anything, to solve or work around the issue?

Deleting the .torrent files from the outputDir of course.

### Additional comments

In both examples I gave above, it seems safe to delete the .torrent from the outputDir, but I don't handle complaints here :)

**Comment by zakkarry** [comment]
@ShanaryS

**Comment by zakkarry** [comment]
They will stop attempting after 24 hours from my understanding, it shouldnt be in perpetuity. I haven't ever seen this, even with injecting thousands of torrents over the weekend multiple times rebuilding my state in Deluge.

Not sure about the specifics of qBittorrent, but there might be other factors like researching and stuff instigating this seeming loop.

**Comment by Audionut** [comment]
Thanks for the feedback. I have one torrent here that's been trying to inject for the last ~3 days. I'll let it keep going in case something is needed from me.

**Comment by ShanaryS** [comment]
This is covered in the docs and linked in the migration guide: https://www.cross-seed.org/docs/tutorials/injection#manual-or-scheduled-injection

Delete the file in outputDir if you aren't going delete the source torrents for the injection as well.

**Comment by Audionut** [comment]
Ah, I didn't think to look outside of the migration guide, nor question myself as to why there was no mention of this in the migration.

I also found the logic for your cleanup criteria. Thanks.

**Comment by ShanaryS** [comment]
![image](https://github.com/user-attachments/assets/b77ad7ab-de83-4187-ae65-e3953fc6401a)

**Comment by zakkarry** [comment]
Honestly, as much as it might shock @Audionut  - lol - I think I might have to agree that the size and number of things in the search improvements section might need a little addressing. Perhaps even an entire "Migrations" section with different pages. I'm not sure (open to thoughts and ideas from anyone though)

It's almost as if we've incrementally ended up with the vast majority being in that heading - although it is for obvious reasons lol - and given its importance and relevance to the app as a whole (imperative details to communicate for migration and users in general) - perhaps we should look into more granularly sectioning out things and clearing it up before we go stable.

Thoughts?

**Comment by Audionut** [comment]
Ah, so looking outside of migrations was not even needed, I still just need to learn to read properly.

The first solution that comes to mind would be further linked subheadings in the directory on the right side, but I'm not sure how messy that would become when accounting for any additional subheadings from sections outside of "search improvements".

I'd like to think I would have clicked "Failed injection" if it was linked in the directory, _and_, actually read it properly.

**Comment by zakkarry** [comment]
One of the largest battles I've had with writing docs, and being a analytical and verbose person to a fault, is that there has been so much improvements and enhancements in addition to the features we've added.

There have been numerous times I've spent hours writing a full novel about explaining things, only show another team member for thoughts and be told "cut that by 60% at least"

Most of the users honestly don't care about the nitty gritty, but that's what people like us enjoy and thrive on.

The fact of the matter is, most people read the docs, if they read them, and set it up and then just let it do its thing. The percentage of people getting really involved in reading them and understanding the features and methodology behind stuff is vastly smaller than the ones who just "trust us bro" - unless of course they run into issues, then its "why wasnt it in the docs i never read to completion" and most of the time I link them to where it was (not implying you, just this is a common trend)....

The fact is we have to strike a careful balance in the docs especially with overwhelming and informing. It's tricky, especially for a person like me who talks alot - particularly on technical issues, and even more so on projects i'm involved with.

The good news is, you can always ask. You know where to find me, and us :)
