### ISSUE TITLE
v6 blockList feature not blocking for me

### ISSUE THREAD

**Issue by StardOva** [cross-seed/cross-seed#820]
### What's happening surrounding the bug? (context)

I use 6.0.0-43 and qbittorrent 5.0.1. I have about 1500 torrents where the majority is music and small sports torrents that I do not wish to cross-seed. Rest is movies, tv and games that I do want to cross-seed. I use qbit categories for the media types (music, sports, tv, games, ....) and tags for individual trackers and other meta stuff (OPS, RED, ...).

This is my blockList:
```javascript
blockList: [
                "tracker:sportscult-announce.org",
                "tracker:home.opsfet.ch",
                "tracker:flacsfor.me",
                "category:sports",
                "category:music",
                "tag:OPS",
                "tag:RED",
                "tag:SportsCult",
                "sizeBelow:1000000000",
        ],
``` 

In theory, each of those blocks (tracker, category, tag, sizeBelow) should be enough to prevent cross-seed from searching these torrents. However, when running `cross-seed search`, it finds 985 torrents that it tries to search for, including the music and sports torrents.

Looking at the debug logs, some torrents are excluded by recent search, while others are excluded by "single episode". But no torrents are excluded with the rules defined in blockList.

### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What should be happening?

tracker, category, tag, sizeBelow should block torrents according to the configuration file.

### Your setup

```markdown
- OS: Debian 12 (seedhost shared seedbox)
- Prowlarr/Jackett: Torznab via Prowlarr 1.25.4.4818
- node: 20.17.0
- Misc:
```

### config.js (REDACT SENSITIVE INFORMATION)

2024-11-01 13:37:09 verbose: [configdump] {
  delay: 30,
  torznab: [
    'https://[REDACTED]/23/api?apikey=[REDACTED]', // these are mostly movie / tv / general trackers
    'https://[REDACTED]/28/api?apikey=[REDACTED]',
    'https://[REDACTED]/25/api?apikey=[REDACTED]',
    'https://[REDACTED]/27/api?apikey=[REDACTED]',
    'https://[REDACTED]/24/api?apikey=[REDACTED]',
    'https://[REDACTED]/15/api?apikey=[REDACTED]',
    'https://[REDACTED]/5/api?apikey=[REDACTED]',
    'https://[REDACTED]/13/api?apikey=[REDACTED]',
    'https://[REDACTED]/3/api?apikey=[REDACTED]',
    'https://[REDACTED]/4/api?apikey=[REDACTED]',
    'https://[REDACTED]/2/api?apikey=[REDACTED]'
  ],
  dataDirs: [],
  matchMode: 'safe',
  linkCategory: 'cross-seed-link',
  linkDir: '/[REDACTED]/data/torrents/cross-seed-link',
  linkType: 'hardlink',
  flatLinking: false,
  maxDataDepth: 2,
  torrentDir: '/[REDACTED]/.local/share/qBittorrent/BT_backup',
  outputDir: '.',
  includeSingleEpisodes: false,
  includeNonVideos: true,
  fuzzySizeThreshold: 0.02,
  excludeOlder: 1209600000,
  excludeRecentSearch: 259200000,
  action: 'inject',
  qbittorrentUrl: 'https://[REDACTED]:[REDACTED]@[REDACTED]/qbittorrent',
  duplicateCategories: true,
  snatchTimeout: 30000,
  searchTimeout: 120000,
  searchLimit: 1000,
  verbose: true,
  blockList: [
    'tracker:sportscult-announce.org',
    'tracker:home.opsfet.ch',
    'tracker:flacsfor.me',
    'category:sports',
    'category:music',
    'tag:OPS',
    'tag:RED',
    'tag:SportsCult',
    'sizeBelow:1000000000'
  ],
  radarr: [],
  sonarr: []
}

### verbose logs

[cross-seed-logs.txt](https://github.com/user-attachments/files/17599748/cross-seed-logs.txt)

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
![image](https://github.com/user-attachments/assets/d0eba210-8f0f-4a72-9abb-84aba6a18dd6)
![image](https://github.com/user-attachments/assets/0af53dbb-cb1e-4045-bd23-443746f3c9c7)

None of those prefixes are implemented in the pre-releases. As noted in the documentation.

**Comment by StardOva** [comment]
Hi, thanks for the quick response. 

I found these issues in my research: https://github.com/cross-seed/cross-seed/issues/210 and https://github.com/cross-seed/cross-seed/issues/95 both being closed indicating that it is already there. Then again, this PR which I suppose will implement this, is still open: https://github.com/cross-seed/cross-seed/pull/773

Thats what confused me a bit. But thanks for clarification!

**Comment by zakkarry** [comment]
Also, in the mean time my qbit_cat_filter script on the starrscripts repo might be helpful.

https://github.com/bakerboy448/StarrScripts

Alternatively, these are implemented on the nightly branch however it is experimental/testing features, and subject to change without notice. 

If you need support for this, please seek it through the Discord as that is our primary means of communication.
