### ISSUE TITLE
missing torrents files fails whole execution

### ISSUE THREAD

**Issue by scratchmex** [cross-seed/cross-seed#839]
### What's happening surrounding the bug? (context)

I am using symlinks. But whenever I delete the original files, it fails following executions because the link is now dangling. We should try catch the `statSync` in `searchee.js` and just skip the torrent processing

The current workaround is to remove the torrent with missing files (dangling links)

### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### Reproducing the bug

1. use symlinks
2. cross-seed 1 torrent
3. remove original torrent with its files
4. cross-seed wil stop to work

### What should be happening?

it should not fail critically and it should just avoid the torrent as it's wrong

### Your setup

```markdown
- OS: Debian
- Prowlarr/Jackett: NA
- Docker: NA
- Misc: NA
```

### config.js (REDACT SENSITIVE INFORMATION)

symlink mode

### verbose logs

```
2024-12-16 04:49:48 info: [scheduler] starting job: search
2024-12-16 04:49:48 info: [scheduler] starting job: inject
2024-12-16 04:49:48 info: [inject] Found 1 torrent file(s) to inject in .
2024-12-16 04:49:48 error: Error: ENOENT: no such file or directory, stat '/downloads/data/cross-seed-link/The.Kings.of.Tupelo.A.Southern.Crime.Saga.S01.DOC.MULTI.1080p.WEB.x264-Penrose/The.Kings.of.Tupelo.A.Southern.Crime.Saga.S01E01.DOC.MULTI.1080p.WEB.x264-Penrose/Sample/the.kings.of.tupelo.a.southern.crime.saga.s01e01.doc.multi.1080p.web.x264-penrose-sample.mkv'
    at statSync (node:fs:1666:25)
    at file:///usr/src/cross-seed/dist/searchee.js:52:17
    at Array.map (<anonymous>)
    at getFilesFromDataRoot (file:///usr/src/cross-seed/dist/searchee.js:49:46)
    at createSearcheeFromPath (file:///usr/src/cross-seed/dist/searchee.js:132:19)
    at Array.map (<anonymous>)
    at findAllSearchees (file:///usr/src/cross-seed/dist/pipeline.js:239:86)
    at async Job.injectSavedTorrents [as exec] (file:///usr/src/cross-seed/dist/inject.js:417:23)
    at async Job.run (file:///usr/src/cross-seed/dist/jobs.js:29:17)
```

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by ShanaryS** [comment]
Why not just prevent dangling symlinks? What's the benefit? Or use hardlinks?

Fixing this one symptom seems like sweeping it under the rug.

> The current workaround is to remove the torrent with missing files (dangling links)

This does not sound like a workaround, but the solution.

**Comment by scratchmex** [comment]
I agree I should not have dangling links. But I don't think that should break the execution. The problem is I don't know if I have the problem until I go to the logs. Hard links would solve the issue but still I think we should fail gracefully

**Comment by ShanaryS** [comment]
This should be handled better but it's also a bigger issue than this application.

**Comment by zakkarry** [comment]
This is just one of the consequences of using symlinks in my mind, you need to manage your links vs original files manually.

The solution you are proposing seems like a way to end up with loads and loads of broken symlinks left on your system with no reason to address or handle them.

**Comment by mmgoodnow** [comment]
Broken symlinks aren't necessarily a bad thing. We should just skip this one searchee

@scratchmex if you switch from dataDirs to torrentDir this should go away. Or minimize dataDirs usage to just files that have been renamed in the past. There is more information on this in the v6 migration guide linked in the README

**Comment by zakkarry** [comment]
> @scratchmex if you switch from dataDirs to torrentDir this should go away. Or minimize dataDirs usage to just files that have been renamed in the past. There is more information on this in the v6 migration guide linked in the README

I'm under the impression that these broken symlinks are left in the client as well, though? Would these not error (eventually?) and then be deleted from the client (preferably "with torrent data") and then be resolved?

What exactly do you mean by "broken symlinks aren't a bad thing" in this context? I haven't ever used them in this context, so I'm unaware of how they could result in anything other than eventual errors in the torrent client (or cross-seed) and invalid referencing to data. That seems like a bad thing, even if it was just isolated to the torrent client error'ing?

**Comment by scratchmex** [comment]
for some reason the torrent doesn't error out with the broken links.

@mmgoodnow will check the datadir thing

**Comment by zakkarry** [comment]
> for some reason the torrent doesn't error out with the broken links.
> 
> @mmgoodnow will check the datadir thing

When a peice is requested it should...

**Comment by scratchmex** [comment]
@zakkarry so skipping them makes sense then. Eventually the error will pop up in the UI even if we don't check the logs

Having it break the whole execution seems too drastic to me

**Comment by scratchmex** [comment]
@zakkarry so skipping them makes sense then. Eventually the error will pop up in the UI even if we don't check the logs

Having it break the whole execution seems too drastic to me
