### ISSUE TITLE
[qBittorrent] user-configurable category

### ISSUE THREAD

**Issue by Technoguyfication** [cross-seed/cross-seed#98]
Hello! Just want to say I love this software and I'm so glad I found it!

I'm using the inject option with qBittorrent right now, I see that the cross-seeded torrents are tagged with `cross-seed`, but I'd also like them to be added to my category for seeding torrents. Is it possible to add an option for us to automatically add cross-seeded torrents to a category of our choice?

**Comment by bobokun** [comment]
@Technoguyfication  if you're interested, [qbit_manage](https://github.com/StuffAnThings/qbit_manage) handles updating categories.

**Comment by kaizensh** [comment]
Would love this because it's messing with my Arr categories

**Comment by baldygeraldy** [comment]
> Would love this because it's messing with my Arr categories

Likewise. Hoping it is solved soon. Season packs are rough without this ability.

**Comment by kaizensh** [comment]
> > Would love this because it's messing with my Arr categories
> 
> Likewise. Hoping it is solved soon. Season packs are rough without this ability.

Yes, while I do use the "Import category" if I have a large queue, it tends to not be able to import all of the shows before cross seed hits which causes duped entries. If sonarr can import fast enough to change the category then cross seed hits, it's okay but yaaa.

**Comment by Vandekieft** [comment]
> > > Would love this because it's messing with my Arr categories
> > 
> > 
> > Likewise. Hoping it is solved soon. Season packs are rough without this ability.
> 
> Yes, while I do use the "Import category" if I have a large queue, it tends to not be able to import all of the shows before cross seed hits which causes duped entries. If sonarr can import fast enough to change the category then cross seed hits, it's okay but yaaa.

I had this issue as well when I was using "Run external program on torrent completion" in qB.. I made a script and added a short delay and it seems to be working. 

Run program `/your/path/delay-post.sh "%I"`


`#!/bin/bash

# Sleep for 5 minutes (300 seconds) #I use 180 seconds
sleep 300


# Your original curl command
curl -XPOST http://localhost:2468/api/webhook?apikey=YOUR_API_KEY --data-urlencode "infoHash=${1}"
`

**Comment by ShanaryS** [comment]
You can do this on v6. If linking is enabled, all torrents will be linked and thus use `linkCategory`. I'm not sure if that is sufficient.
